from __future__ import annotations

from telegram_proxy.runtime.commands import (
    TelegramProxyActionResult,
    TelegramProxyDiagnosticsFinishPlan,
    TelegramProxyDiagnosticsPollPlan,
    TelegramProxyDiagnosticsStartPlan,
    TelegramProxyStartConfig,
    append_log_line,
    build_diagnostics_finish_plan,
    build_diagnostics_poll_plan,
    build_diagnostics_start_plan,
    consume_auto_deeplink_request,
    copy_text,
    open_external_link,
    open_log_file,
    run_diagnostics,
    run_telegram_hosts_action,
    set_enabled,
    start_proxy_if_enabled_async,
)

__all__ = [
    "TelegramProxyActionResult",
    "TelegramProxyDiagnosticsFinishPlan",
    "TelegramProxyDiagnosticsPollPlan",
    "TelegramProxyDiagnosticsStartPlan",
    "TelegramProxyStartConfig",
    "append_log_line",
    "build_diagnostics_finish_plan",
    "build_diagnostics_poll_plan",
    "build_diagnostics_start_plan",
    "consume_auto_deeplink_request",
    "copy_text",
    "open_external_link",
    "open_log_file",
    "run_diagnostics",
    "run_telegram_hosts_action",
    "set_enabled",
    "start_proxy_if_enabled_async",
]
