"""Разбор текста Windows hosts на блоки: чей блок и какие в нём строки.

Нужен разделу «Что в hosts»: пользователь видит всё, что программа и он сам
записали в файл. Здесь только чтение текста, файл не открывается.
"""

from __future__ import annotations

from dataclasses import dataclass


BLOCK_ZAPRETGUI = "zapretgui"
BLOCK_TELEGRAM = "telegram"
BLOCK_MAX = "max"
BLOCK_STATE_MEDIA = "state_media"
BLOCK_ADOBE = "adobe"
BLOCK_USER = "user"

BLOCK_ORDER = (
    BLOCK_ZAPRETGUI,
    BLOCK_TELEGRAM,
    BLOCK_MAX,
    BLOCK_STATE_MEDIA,
    BLOCK_ADOBE,
    BLOCK_USER,
)

# Маркеры повторяют то, что пишут владельцы блоков:
# hosts/hosts.py, telegram_proxy/telegram_hosts.py, windows_features/max_blocker.py,
# windows_features/state_media_blocker.py.
_BEGIN_END_MARKERS = {
    "# >>> zapretgui:hosts managed begin >>>": ("# <<< zapretgui:hosts managed end <<<", BLOCK_ZAPRETGUI),
    "# MAX BLOCKED BY ZAPRET GUI": ("# END MAX BLOCK", BLOCK_MAX),
    "# >>> zapretgui:russian-state-media-block begin >>>": (
        "# <<< zapretgui:russian-state-media-block end <<<",
        BLOCK_STATE_MEDIA,
    ),
}
# У этих блоков нет строки конца: блок — это идущие подряд записи после заголовка.
_HEADER_ONLY_MARKERS = {
    "# --- Telegram Proxy (auto-managed by Zapret 2 GUI) ---": BLOCK_TELEGRAM,
    "# Adobe Activation Block": BLOCK_ADOBE,
    "# Adobe Block": BLOCK_ADOBE,
}


@dataclass(frozen=True, slots=True)
class HostsBlock:
    kind: str
    lines: tuple[str, ...]

    @property
    def count(self) -> int:
        return len(self.lines)


def is_mapping_line(line: str) -> bool:
    """Строка-запись вида «адрес имя», а не пустая строка или комментарий."""
    mapping = str(line or "").partition("#")[0].split()
    return len(mapping) >= 2


def mapping_domains(line: str) -> list[str]:
    parts = str(line or "").partition("#")[0].split()
    return parts[1:] if len(parts) >= 2 else []


def parse_hosts_blocks(text: str) -> list[HostsBlock]:
    """Возвращает непустые блоки в порядке BLOCK_ORDER."""
    lines_by_kind: dict[str, list[str]] = {kind: [] for kind in BLOCK_ORDER}
    open_end: str | None = None
    open_kind: str | None = None
    header_kind: str | None = None

    for raw_line in str(text or "").splitlines():
        stripped = raw_line.strip()

        if open_kind is not None:
            if stripped == open_end:
                open_kind = None
                open_end = None
            elif is_mapping_line(stripped):
                lines_by_kind[open_kind].append(stripped)
            continue

        begin = _BEGIN_END_MARKERS.get(stripped)
        if begin is not None:
            open_end, open_kind = begin
            header_kind = None
            continue

        header = _HEADER_ONLY_MARKERS.get(stripped)
        if header is not None:
            header_kind = header
            continue

        if header_kind is not None:
            if is_mapping_line(stripped):
                lines_by_kind[header_kind].append(stripped)
                continue
            if stripped.startswith("#") and stripped:
                # Служебная строка под заголовком («# Generated by …»).
                continue
            header_kind = None

        if is_mapping_line(stripped):
            lines_by_kind[BLOCK_USER].append(stripped)

    return [
        HostsBlock(kind=kind, lines=tuple(lines_by_kind[kind]))
        for kind in BLOCK_ORDER
        if lines_by_kind[kind]
    ]


__all__ = [
    "BLOCK_ADOBE",
    "BLOCK_MAX",
    "BLOCK_ORDER",
    "BLOCK_STATE_MEDIA",
    "BLOCK_TELEGRAM",
    "BLOCK_USER",
    "BLOCK_ZAPRETGUI",
    "HostsBlock",
    "is_mapping_line",
    "mapping_domains",
    "parse_hosts_blocks",
]
