"""Разбор текста Windows hosts на блоки: чей блок и какие в нём строки.

Нужен странице «Файл hosts»: строки раскрашены по владельцу, рядом счётчики.
Здесь только чтение текста, файл не открывается.
"""

from __future__ import annotations

from dataclasses import dataclass


BLOCK_ZAPRETGUI = "zapretgui"
BLOCK_TELEGRAM = "telegram"
BLOCK_MAX = "max"
BLOCK_STATE_MEDIA = "state_media"
BLOCK_ADOBE = "adobe"
BLOCK_USER = "user"

BLOCK_ORDER = (
    BLOCK_ZAPRETGUI,
    BLOCK_TELEGRAM,
    BLOCK_MAX,
    BLOCK_STATE_MEDIA,
    BLOCK_ADOBE,
    BLOCK_USER,
)

# Маркеры повторяют то, что пишут владельцы блоков:
# hosts/hosts.py, telegram_proxy/telegram_hosts.py, windows_features/max_blocker.py,
# windows_features/state_media_blocker.py.
_BEGIN_END_MARKERS = {
    "# >>> zapretgui:hosts managed begin >>>": ("# <<< zapretgui:hosts managed end <<<", BLOCK_ZAPRETGUI),
    "# MAX BLOCKED BY ZAPRET GUI": ("# END MAX BLOCK", BLOCK_MAX),
    "# >>> zapretgui:russian-state-media-block begin >>>": (
        "# <<< zapretgui:russian-state-media-block end <<<",
        BLOCK_STATE_MEDIA,
    ),
}
# У этих блоков нет строки конца: блок — это идущие подряд записи после заголовка.
_HEADER_ONLY_MARKERS = {
    "# --- Telegram Proxy (auto-managed by Zapret 2 GUI) ---": BLOCK_TELEGRAM,
    "# Adobe Activation Block": BLOCK_ADOBE,
    "# Adobe Block": BLOCK_ADOBE,
}


@dataclass(frozen=True, slots=True)
class HostsBlock:
    kind: str
    lines: tuple[str, ...]

    @property
    def count(self) -> int:
        return len(self.lines)


# Роль строки в файле.
ROLE_ENTRY = "entry"      # запись «адрес имя»
ROLE_MARKER = "marker"    # служебный заголовок или конец блока
ROLE_COMMENT = "comment"
ROLE_BLANK = "blank"

# Состояние разбора между строками — целое число, чтобы его можно было хранить
# в QSyntaxHighlighter (setCurrentBlockState): 0 — вне блоков,
# 1..N — внутри блока «начало/конец», 100+N — под заголовком без конца.
STATE_NONE = 0
_HEADER_STATE_BASE = 100
_END_MARKER_BY_KIND = {kind: end for _begin, (end, kind) in _BEGIN_END_MARKERS.items()}


def _kind_state(kind: str, *, header: bool) -> int:
    index = BLOCK_ORDER.index(kind) + 1
    return _HEADER_STATE_BASE + index if header else index


def _state_kind(state: int) -> tuple[str | None, bool]:
    if state <= STATE_NONE:
        return None, False
    header = state >= _HEADER_STATE_BASE
    index = state - _HEADER_STATE_BASE if header else state
    if not 1 <= index <= len(BLOCK_ORDER):
        return None, False
    return BLOCK_ORDER[index - 1], header


def is_mapping_line(line: str) -> bool:
    """Строка-запись вида «адрес имя», а не пустая строка или комментарий."""
    mapping = str(line or "").partition("#")[0].split()
    return len(mapping) >= 2


def mapping_domains(line: str) -> list[str]:
    parts = str(line or "").partition("#")[0].split()
    return parts[1:] if len(parts) >= 2 else []


def classify_hosts_line(line: str, state: int = STATE_NONE) -> tuple[str | None, str, int]:
    """Чья строка и что это за строка.

    Возвращает (владелец или None, роль, состояние для следующей строки).
    Владелец None бывает только у комментариев и пустых строк вне блоков.
    """
    stripped = str(line or "").strip()
    kind, header = _state_kind(state)

    if kind is not None and not header:
        if stripped == _END_MARKER_BY_KIND[kind]:
            return kind, ROLE_MARKER, STATE_NONE
        if is_mapping_line(stripped):
            return kind, ROLE_ENTRY, state
        return kind, (ROLE_COMMENT if stripped else ROLE_BLANK), state

    begin = _BEGIN_END_MARKERS.get(stripped)
    if begin is not None:
        return begin[1], ROLE_MARKER, _kind_state(begin[1], header=False)

    header_kind = _HEADER_ONLY_MARKERS.get(stripped)
    if header_kind is not None:
        return header_kind, ROLE_MARKER, _kind_state(header_kind, header=True)

    if kind is not None and header:
        if is_mapping_line(stripped):
            return kind, ROLE_ENTRY, state
        if stripped.startswith("#"):
            # Служебная строка под заголовком («# Generated by …»).
            return kind, ROLE_COMMENT, state
        # Пустая строка или что-то другое заканчивает блок без конца.

    if is_mapping_line(stripped):
        return BLOCK_USER, ROLE_ENTRY, STATE_NONE
    return None, (ROLE_COMMENT if stripped else ROLE_BLANK), STATE_NONE


def parse_hosts_blocks(text: str) -> list[HostsBlock]:
    """Возвращает непустые блоки записей в порядке BLOCK_ORDER."""
    lines_by_kind: dict[str, list[str]] = {kind: [] for kind in BLOCK_ORDER}
    state = STATE_NONE
    for raw_line in str(text or "").splitlines():
        kind, role, state = classify_hosts_line(raw_line, state)
        if kind is not None and role == ROLE_ENTRY:
            lines_by_kind[kind].append(raw_line.strip())
    return [
        HostsBlock(kind=kind, lines=tuple(lines_by_kind[kind]))
        for kind in BLOCK_ORDER
        if lines_by_kind[kind]
    ]


__all__ = [
    "ROLE_BLANK",
    "ROLE_COMMENT",
    "ROLE_ENTRY",
    "ROLE_MARKER",
    "STATE_NONE",
    "BLOCK_ADOBE",
    "BLOCK_MAX",
    "BLOCK_ORDER",
    "BLOCK_STATE_MEDIA",
    "BLOCK_TELEGRAM",
    "BLOCK_USER",
    "BLOCK_ZAPRETGUI",
    "HostsBlock",
    "classify_hosts_line",
    "is_mapping_line",
    "mapping_domains",
    "parse_hosts_blocks",
]
