from __future__ import annotations

from hosts.commands import (
    add_adobe_domains,
    apply_service_profiles,
    clear_hosts,
    create_hosts_runtime,
    execute_hosts_operation,
    get_catalog_signature,
    get_hosts_path_str,
    get_hosts_state,
    build_services_catalog_plan,
    invalidate_catalog_cache,
    load_user_selection,
    open_hosts_file,
    read_hosts_file,
    read_active_domains_map,
    refresh_applied_selection,
    remove_adobe_domains,
    restore_hosts_permissions,
    save_user_selection,
    write_hosts_file,
)
from hosts.state import HostsCommandResult, HostsState

__all__ = [
    "HostsCommandResult",
    "HostsState",
    "add_adobe_domains",
    "apply_service_profiles",
    "clear_hosts",
    "create_hosts_runtime",
    "execute_hosts_operation",
    "get_catalog_signature",
    "get_hosts_path_str",
    "get_hosts_state",
    "build_services_catalog_plan",
    "invalidate_catalog_cache",
    "load_user_selection",
    "open_hosts_file",
    "read_hosts_file",
    "read_active_domains_map",
    "refresh_applied_selection",
    "remove_adobe_domains",
    "restore_hosts_permissions",
    "save_user_selection",
    "write_hosts_file",
]
