"""Английский перевод шуток под заголовками итогов (см. ``fun_state_lines_ru.py``)."""

from __future__ import annotations

EN: dict[str, tuple[str, ...]] = {
    "stopped": (
        "RKN-chan breathes out",
        "Zapret-chan: «Right at the best part»",
        "The TSPU box wipes its brow",
        "The honey badger sat down where it stood",
        "Stormtrooper RX-78 welcomes the break",
        "The suspense remains",
        "Zapret-chan puts the stethoscope away",
        "RKN-chan: «Good call». Debatable",
        "The black boxes exchange glances",
        "The honey badger isn't offended. It can't be",
        "Zapret-chan waits for the sequel",
        "Stopped mid-sentence",
        "The TSPU box thinks it won",
        "RKN-chan hides a smile",
        "The list is left unread",
        "Zapret-chan puffs her cheeks",
        "The honey badger went for tea",
        "Too early for conclusions",
        "Stormtrooper RX-78 takes off the helmet",
        "RKN-chan: «Phew»",
        "Zapret-chan: «I'll be back»",
        "Not everyone got to answer",
        "The TSPU box pretends to be asleep again",
        "Intermission",
        "The honey badger folds its notebook",
        "Zapret-chan didn't finish her rounds",
        "RKN-chan twirls her handcuffs out of boredom",
        "Start again whenever you like",
        "Until next time, black boxes",
        "Zapret-chan taps her heel",
    ),
    "error": (
        "Zapret-chan sighs",
        "The honey badger scratches its head",
        "RKN-chan, stop giggling",
        "The TSPU box acts like it wasn't involved",
        "It happens. Let's try again",
        "Zapret-chan: «Right, from the top»",
        "Stormtrooper RX-78 looks away",
        "First pancake is always lumpy",
        "A fiasco, but a fixable one",
        "Zapret-chan will peek at the log",
        "The honey badger isn't upset",
        "RKN-chan covers a giggle with her hand",
        "We dropped everything. We'll pick it up",
        "Zapret-chan takes a second attempt",
        "The black boxes stay silent",
        "Meh. Let's try once more",
        "Zapret-chan adjusts her glasses",
        "RKN-chan: «Oops». Us: «Oops»",
        "Details are in the log below",
        "The honey badger growls at the failure",
        "Zapret-chan doesn't give up",
        "Too early to press F",
        "The TSPU box is celebrating too early",
        "Zapret-chan: «Again»",
        "RKN-chan nods in sympathy. She's faking",
        "No harm in trying",
        "The honey badger is ready to go again",
        "Zapret-chan looks for where we tripped",
        "Houston, we have a hiccup",
        "Please try again",
    ),
    "bc_idle": (
        "RKN-chan hopes you never check",
        "Zapret-chan has already rolled up her sleeves",
        "The honey badger awaits the command",
        "The TSPU box sleeps peacefully, for now",
        "Stormtrooper RX-78 relaxed too soon",
        "High time to learn the truth",
        "Zapret-chan taps the «Check» button",
        "What if it all works? Kidding",
        "RKN-chan pretends she isn't here",
        "The bored honey badger sniffs the cable",
        "The black boxes have gone quiet",
        "The «Check» button has been waiting",
        "Zapret-chan: «Come on already»",
        "What the TSPU box did is still a mystery",
        "RKN-chan hides her whip behind her back",
        "The suspense is intact",
        "The honey badger sharpens its claws",
        "Zapret-chan is ready for her rounds",
        "The TSPU box hopes for the best",
        "«Works on my machine» — shall we check?",
        "RKN-chan: «No need!» There is",
        "No diagnosis without tests",
        "Zapret-chan put on a coat and a stethoscope",
        "Is the walled garden creeping in?",
        "The honey badger yawns and waits",
        "Maybe something «degraded»",
        "Stormtrooper RX-78 is counting crows",
        "Zapret-chan leafs through the site list",
        "Press it and RKN-chan will flinch",
        "Zapret-chan and the badger are in the blocks",
    ),
    "bc_ok": (
        "RKN-chan is heartbroken",
        "Zapret-chan is pleased with herself",
        "The TSPU box weeps quietly in its rack",
        "The honey badger holds its tail high",
        "Stormtrooper RX-78 is writing an explanation",
        "RKN-chan: «That's not fair!»",
        "Zapret-chan drops a curtsy",
        "Chin up, black boxes",
        "No «degradation» at all",
        "RKN-chan puffs her cheeks",
        "Zapret-chan: «Don't mention it»",
        "The TSPU box asks for a day off",
        "The honey badger allows a pat",
        "A window to the world, not a peephole",
        "RKN-chan looks for something to nitpick",
        "Zapret-chan straightens her bow",
        "Nothing to press F for",
        "Stormtrooper RX-78 is stunned",
        "RKN-chan dropped her banhammer",
        "Zapret-chan and the badger high-five",
        "TSPU box: «It did it by itself!» Sure",
        "You can breathe out",
        "RKN-chan: «I just looked away»",
        "Zapret-chan snaps her fingers in triumph",
        "The walled garden didn't sneak in",
        "The honey badger dances, shyly",
        "RKN-chan checks her list. Empty",
        "Zapret-chan: «Did you doubt me?»",
        "Thanks for a day without a ban",
        "Zapret-chan blows RKN-chan a kiss",
    ),
    "bc_unknown": (
        "RKN-chan shrugs",
        "Zapret-chan frowns",
        "The TSPU box keeps silent like a spy",
        "The honey badger scratches its neck",
        "Stormtrooper RX-78 «saw nothing»",
        "Silence is an answer too, a vague one",
        "Zapret-chan will ask again",
        "RKN-chan: «No comment»",
        "The black boxes won't say a word",
        "Somebody didn't pick up",
        "The honey badger knocked; nobody opened",
        "Zapret-chan draws question marks",
        "The TSPU box pretends it didn't hear",
        "RKN-chan studies the ceiling",
        "Somebody stepped out for a minute",
        "The question hangs in the air",
        "Zapret-chan: «Why is this one quiet?»",
        "Not everyone showed up for roll call",
        "RKN-chan whistles a tune",
        "The honey badger notes: «No answer»",
        "Zapret-chan dislikes loose ends",
        "Some answers are still on the road",
        "The TSPU box would shrug, if it could",
        "«The subscriber is unavailable»",
        "RKN-chan bats her lashes innocently",
        "Zapret-chan will knock again",
        "The echo is more talkative",
        "The honey badger squints suspiciously",
        "Zapret-chan keeps her notebook open",
        "Try again a little later",
    ),
    "bc_problems": (
        "RKN-chan did her best",
        "Zapret-chan rolls up her sleeves",
        "The TSPU box hasn't been idle",
        "The honey badger is already sharpening claws",
        "Stormtrooper RX-78 is proud. Wrongly",
        "We'll sort it out",
        "RKN-chan: «Wasn't me!» Sure",
        "Zapret-chan grabs a notebook and goes fixing",
        "The black boxes have been busy",
        "It's fine, we've seen worse",
        "RKN-chan hides handcuffs behind her back",
        "Zapret-chan: «Well, what have we here»",
        "The TSPU box looks down modestly",
        "The honey badger is not impressed",
        "The list is below, and so is the cure",
        "RKN-chan left her autograph",
        "Zapret-chan knows what to do",
        "«It did it by itself», right",
        "Stormtrooper RX-78 left footprints",
        "Zapret-chan adjusts her gloves",
        "RKN-chan cracked her whip. We noticed",
        "This is treatable",
        "TSPU box: «So what?»",
        "The honey badger goes to deal with it",
        "Zapret-chan is already browsing strategies",
        "RKN-chan winks. Not a good sign",
        "We'll widen the peephole into a window",
        "Someone «throttled» it. Who could it be",
        "Zapret-chan: «On it»",
        "Details below",
    ),
    "dns_idle": (
        "Zapret-chan will hold the notebook",
        "RKN-chan is blushing in advance",
        "The TSPU box makes honest eyes",
        "The directory is under suspicion",
        "Stormtrooper RX-78 hides the eraser",
        "Zapret-chan already has her loupe out",
        "RKN-chan: «Why me straight away?»",
        "The lie detector is warmed up",
        "Zapret-chan takes nobody's word for it",
        "The TSPU box nervously flips the address book",
        "What if it says 127.0.0.1",
        "RKN-chan straightens the house numbers",
        "Is it always DNS? We'll find out",
        "Zapret-chan: «Trust, but verify»",
        "The black boxes are not guilty in advance",
        "The ISP's directory is called in for questions",
        "RKN-chan tucks a pencil behind her ear",
        "Zapret-chan switches on the desk lamp",
        "The honey badger doesn't trust road signs",
        "TSPU box: «We never touch addresses». We'll see",
        "A face-off of directories is near",
        "RKN-chan fiddles with her braid",
        "Zapret-chan will check every address",
        "The truth is out there",
        "Did Stormtrooper RX-78 move the signposts?",
        "Zapret-chan puts on detective glasses",
        "RKN-chan: «I only fixed it a tiny bit»",
        "Proof will follow",
        "Zapret-chan sharpens her pencil",
        "The honey badger sniffs at the directory",
    ),
    "dns_ok": (
        "RKN-chan had nothing to do with it. This time",
        "Zapret-chan nods approvingly",
        "The TSPU box is squeaky clean. Surprising",
        "The honey badger shakes the directory's paw",
        "Stormtrooper RX-78 left the signposts alone",
        "Zapret-chan puts the loupe away",
        "RKN-chan: «Told you!»",
        "Addresses match to the last digit",
        "Zapret-chan gives it top marks",
        "The black boxes are off the hook",
        "The directory didn't lie once",
        "RKN-chan lifts her nose in triumph",
        "It wasn't DNS. It happens",
        "Zapret-chan: «Clean. Moving on»",
        "The TSPU box breathes out",
        "The honey badger is pleased, which is rare",
        "The lie detector stayed silent",
        "RKN-chan demands an apology",
        "Zapret-chan closes her notebook",
        "Not a single doctored digit",
        "Stormtrooper RX-78 is acquitted",
        "The directory can be trusted",
        "Zapret-chan takes off the detective glasses",
        "RKN-chan: «So who's lying now?»",
        "The face-off ended peacefully",
        "TSPU box: «We never touch addresses». True",
        "Zapret-chan shakes hands with the directory",
        "The honey badger retracts its claws",
        "RKN-chan straightens her tie with dignity",
        "Zapret-chan switches off the desk lamp",
    ),
    "dns_spoofed": (
        "RKN-chan turned red",
        "Zapret-chan clicks handcuffs. Her own",
        "The TSPU box got caught with an eraser",
        "The honey badger growls at the directory",
        "Stormtrooper RX-78 moved the signposts",
        "Zapret-chan: «Gotcha»",
        "RKN-chan: «Not spoofing, a clarification»",
        "A digit has been doctored",
        "Zapret-chan lays the evidence on the table",
        "The black boxes avoid eye contact",
        "The directory lied",
        "RKN-chan hides the pencil",
        "Encrypted DNS is beyond their reach",
        "Zapret-chan knows the cure: DoH",
        "TSPU box: «It did it by itself». No",
        "The honey badger calls for witnesses",
        "RKN-chan bites her lip",
        "Zapret-chan takes down the testimony",
        "Wrong address, familiar handwriting",
        "Stormtrooper RX-78 stares at the floor",
        "Zapret-chan: «Well, well, well»",
        "RKN-chan: «Prove it!» Proved",
        "The lie detector is off the scale",
        "Zapret-chan puts on gloves",
        "The TSPU box gave itself away",
        "The house numbers were swapped",
        "RKN-chan asks us to keep it down",
        "Zapret-chan is already bringing encryption",
        "The honey badger dislikes liars",
        "Proof attached",
    ),
    "dns_partial": (
        "RKN-chan sighs with relief",
        "Zapret-chan still squints",
        "The TSPU box seems to have behaved",
        "The honey badger hides its claws, partly",
        "Stormtrooper RX-78 is under observation",
        "But that's not certain",
        "Zapret-chan left a couple of question marks",
        "RKN-chan: «There, you see!»",
        "Some addresses wander around by themselves",
        "Zapret-chan: «Fine, I believe you for now»",
        "The black boxes are suspects without evidence",
        "RKN-chan smiles carefully",
        "Zapret-chan holds her notebook open",
        "The TSPU box got off with a scare",
        "The honey badger sniffs but says nothing",
        "Not enough evidence",
        "RKN-chan fixes her hair",
        "Zapret-chan: «Doubtful, but okay»",
        "Every digit is in place",
        "Stormtrooper RX-78 wipes his forehead",
        "Zapret-chan keeps an eye on the directory",
        "RKN-chan isn't involved. It seems",
        "The directory mumbles but doesn't lie",
        "TSPU box: «I'm clean». We almost believe it",
        "Zapret-chan taps her pencil",
        "The honey badger keeps its own opinion",
        "RKN-chan plays the angel",
        "Zapret-chan will check again someday",
        "Sleep well, with one eye open",
        "Zapret-chan pencils in a question mark",
    ),
    "dns_unverified": (
        "The reference didn't pick up",
        "Zapret-chan knits her brows",
        "RKN-chan: «What a pity»",
        "Did the TSPU box block the help desk?",
        "The honey badger knocked, no answer",
        "Stormtrooper RX-78 stands at the door",
        "There was nothing to compare with",
        "Zapret-chan will try again",
        "The black boxes are tight-lipped",
        "The face-off fell through",
        "RKN-chan looks suspiciously pleased",
        "Zapret-chan: «That won't do»",
        "The honest directory is out of range",
        "The TSPU box shrugs",
        "The honey badger is displeased",
        "The lie detector didn't switch on",
        "RKN-chan gazes innocently out the window",
        "Zapret-chan will call the reference back",
        "The witnesses didn't show up",
        "Stormtrooper RX-78 «touched nothing»",
        "Zapret-chan adds a question mark",
        "The subscriber is temporarily unavailable",
        "RKN-chan: «Not my doing». Possibly",
        "Zapret-chan is stubborn: she'll call again",
        "No reference, no conclusions",
        "The TSPU box is glad it blew over",
        "The honey badger will wait",
        "Zapret-chan looks up spare numbers",
        "RKN-chan adjusts her bow",
        "Try later",
    ),
    "srv_idle": (
        "Zapret-chan reads out the numbers",
        "RKN-chan has already called some of them",
        "The TSPU box is listening in on the line",
        "Three calls each",
        "Stormtrooper RX-78 guards port 53",
        "Zapret-chan holds the stopwatch",
        "RKN-chan: «It's busy». We'll check",
        "Zapret-chan flips through the phone book",
        "The black boxes prick up their ears",
        "We'll see who picks up",
        "Did RKN-chan cut a couple of wires?",
        "Zapret-chan: «Hello, anyone there?»",
        "The honey badger warms up its dialling finger",
        "The TSPU box hopes we won't get through",
        "The help desk never sleeps",
        "Zapret-chan knows the spare numbers",
        "RKN-chan adjusts her earpiece",
        "The calls start with the button",
        "Stormtrooper RX-78 counts the rings",
        "Zapret-chan will check each one three times",
        "Who's quick, and who's «out of range»",
        "RKN-chan pretends to be busy",
        "Zapret-chan puts her headset on",
        "TSPU box: «Line's busy». We don't buy it",
        "The honey badger will find the fastest one",
        "Zapret-chan flexes her fingers",
        "RKN-chan stands at port 53 with a whip",
        "Zapret-chan will go through 443",
        "DoT and DoH sound like dwarf names",
        "Zapret-chan and the badger split the list",
    ),
    "srv_empty": (
        "Zapret-chan spreads her hands",
        "RKN-chan: «Lovely»",
        "The honey badger flips a blank page",
        "The TSPU box is bored",
        "Zapret-chan looks under the desk",
        "Did Stormtrooper RX-78 clean it out?",
        "The phone book is empty",
        "Zapret-chan: «Who am I supposed to call?»",
        "RKN-chan smiles contentedly",
        "The black boxes have nothing to listen to",
        "Add at least one server",
        "The honey badger sniffs the void",
        "Zapret-chan shakes the empty directory",
        "RKN-chan: «Better this way». No",
        "The calls are cancelled",
        "Zapret-chan gazes sadly at the handset",
        "The TSPU box is out of work",
        "Radio silence",
        "Stormtrooper RX-78 guards the emptiness",
        "Zapret-chan waits for numbers",
        "Is RKN-chan hiding the list behind her back?",
        "Nobody to say «hello» to",
        "Zapret-chan put the headset down",
        "The honey badger shrugs",
        "RKN-chan twirls her whip out of boredom",
        "Zapret-chan: «Even one would do»",
        "Add servers first",
        "Empty, like a dream registry",
        "Zapret-chan doodles a flower in her notebook",
        "The honey badger curls up",
    ),
    "srv_intercepted": (
        "RKN-chan picked up somebody else's phone",
        "Zapret-chan brings encryption",
        "The TSPU box answers for others",
        "The honey badger growls at the middleman",
        "Stormtrooper RX-78 is sitting on the line",
        "Zapret-chan: «Caught you»",
        "RKN-chan: «I only helped connect you»",
        "Not who you called on the other end",
        "Zapret-chan pulls out DoH",
        "A black box speaks in a borrowed voice",
        "«Uncle» answers for the server",
        "RKN-chan hides the handset",
        "Zapret-chan puts the conversation under lock",
        "TSPU box: «Hello, I'm answering for him»",
        "The honey badger dislikes middlemen",
        "Letters are opened along the way",
        "RKN-chan fakes a voice. Badly",
        "Zapret-chan knows how to seal an envelope",
        "Stormtrooper RX-78 stands at port 53",
        "Zapret-chan goes through 443",
        "RKN-chan blushes but keeps the phone",
        "They can't read the encrypted one",
        "Zapret-chan clicks the lock",
        "The TSPU box got caught on the line",
        "The honey badger sniffs at the wire",
        "RKN-chan: «It's faster this way!» No",
        "Zapret-chan writes: «middleman found»",
        "Three's a crowd on this wire",
        "Zapret-chan recommends DoH",
        "Switch on encrypted DNS",
    ),
    "srv_spoofed": (
        "RKN-chan edits answers with a red pen",
        "Zapret-chan hurries over with encryption",
        "The TSPU box hands out block pages",
        "The honey badger growls at the lies",
        "Stormtrooper RX-78 paints new signs",
        "Zapret-chan: «A lie. Noted»",
        "RKN-chan: «No such site». There is",
        "A block page instead of an address",
        "Zapret-chan writes a prescription: DoH",
        "A black box makes up addresses",
        "RKN-chan hides the eraser",
        "Zapret-chan knows the remedy",
        "TSPU box: «Site doesn't exist». It does",
        "The honey badger believes none of it",
        "The directory has been rewritten",
        "RKN-chan blushes to her ears",
        "Zapret-chan presents the evidence",
        "Encrypted DNS will tell the truth",
        "Stormtrooper RX-78 studies his boots",
        "Zapret-chan: «Aha, got you»",
        "RKN-chan: «It's a clarification»",
        "Somebody doctored a digit",
        "Zapret-chan pulls on her gloves",
        "The TSPU box was caught lying",
        "The honey badger demands witnesses",
        "RKN-chan winds a braid around her finger",
        "Zapret-chan will seal the answers",
        "The lie detector is beeping",
        "Zapret-chan suggests DoH",
        "They can't forge encrypted DNS",
    ),
    "srv_shaky": (
        "Zapret-chan counts the misses",
        "RKN-chan tugs at the wire",
        "The TSPU box plays «answer, don't answer»",
        "The honey badger redials",
        "Stormtrooper RX-78 lets some in, some not",
        "Now «hello», now silence",
        "Zapret-chan: «How unreliable»",
        "RKN-chan whistles innocently",
        "Every other time is not a service",
        "Zapret-chan hands out C grades",
        "The black boxes have the hiccups",
        "Pick the ones that always answer",
        "RKN-chan: «Bad connection». Right",
        "Zapret-chan flags the moody ones",
        "The TSPU box blinks on the line",
        "The honey badger counts the rings",
        "Servers with character",
        "RKN-chan flicks the switch",
        "Zapret-chan picks the dependable ones",
        "Feast or famine",
        "Stormtrooper RX-78 keeps hitting pause",
        "Zapret-chan taps her stopwatch",
        "RKN-chan makes big eyes",
        "No spoofing, at least",
        "Zapret-chan: «Not these ones»",
        "TSPU box: «Interference». Of course",
        "The honey badger dislikes the moody ones",
        "Zapret-chan knows whom to pick",
        "RKN-chan let go of the wire. For now",
        "Choose the ones marked «Working»",
    ),
    "srv_closed": (
        "RKN-chan hung a padlock on a port",
        "Zapret-chan knows another entrance",
        "The TSPU box stands in the doorway",
        "The honey badger takes the next door",
        "Stormtrooper RX-78 guards a port",
        "If not the door, then the window",
        "Zapret-chan: «That one's shut, try this»",
        "RKN-chan: «Closed for cleaning»",
        "One of the entrances is locked",
        "Zapret-chan jingles the spare keys",
        "The black boxes blocked a passage",
        "The other entrances are open",
        "RKN-chan hides the key",
        "Zapret-chan isn't bothered",
        "TSPU box: «Entrance round the back»",
        "The honey badger knows the back door",
        "Front door closed, staff door open",
        "RKN-chan stands at a port with her whip",
        "Zapret-chan takes the detour",
        "No spoofing in sight",
        "Stormtrooper RX-78 lets nobody through",
        "Zapret-chan: «We'll go around»",
        "RKN-chan straightens the «Closed» sign",
        "All is not lost",
        "Zapret-chan picks the methods that work",
        "The TSPU box didn't block every door",
        "The honey badger doesn't scare easily",
        "Zapret-chan ticks the open ones",
        "RKN-chan didn't manage to close everything",
        "Take servers marked «Working»",
    ),
    "srv_notes": (
        "RKN-chan is disappointed",
        "Zapret-chan is content",
        "The TSPU box was on good behaviour",
        "The honey badger relaxes its tail",
        "Stormtrooper RX-78 barely got in the way",
        "A couple of servers are asleep, so what",
        "Zapret-chan: «We can live with that»",
        "RKN-chan hunts for something to nitpick",
        "Nobody was eavesdropping",
        "Zapret-chan snaps her notebook shut",
        "The black boxes are being good today",
        "No interception, no spoofing",
        "RKN-chan throws up her hands",
        "Zapret-chan gives a B plus",
        "TSPU box: «See?»",
        "The honey badger approves",
        "Just don't pick the silent ones",
        "RKN-chan straightens her tie",
        "Zapret-chan puts the stopwatch away",
        "Small things don't count",
        "Stormtrooper RX-78 is acquitted. Almost",
        "Zapret-chan: «Clean»",
        "RKN-chan wants praise. She'll manage",
        "The answers are honest",
        "Zapret-chan takes off her headset",
        "The TSPU box catches its breath",
        "The honey badger hides its claws",
        "Zapret-chan marked the silent ones",
        "RKN-chan is bored",
        "You can pick a server",
    ),
    "srv_ok": (
        "RKN-chan is sad",
        "Zapret-chan is beaming",
        "The TSPU box didn't touch a single one",
        "The honey badger fluffs its tail",
        "Stormtrooper RX-78 let everyone through",
        "Everyone picked up",
        "Zapret-chan hands out A grades",
        "RKN-chan: «That never happens!»",
        "No interception and no spoofing",
        "Zapret-chan bows to the audience",
        "The black boxes are resting",
        "The calls went like clockwork",
        "RKN-chan turns away in a huff",
        "Zapret-chan: «Exemplary»",
        "The TSPU box took the day off",
        "The honey badger purrs. Yes, they can",
        "The line is clean",
        "RKN-chan dropped her whip",
        "Zapret-chan hangs her headset on the hook",
        "Everybody is on the line",
        "Stormtrooper RX-78 drafts an explanation",
        "Zapret-chan admires the result",
        "RKN-chan found nothing to nitpick",
        "Pick any of them",
        "Zapret-chan clicks the stopwatch in triumph",
        "TSPU box: «By itself». This time, yes",
        "The honey badger does a little dance",
        "Zapret-chan: «I told you so»",
        "RKN-chan acts like that was the plan",
        "A good day without a ban",
    ),
    "scan_idle": (
        "Zapret-chan fans out the strategies",
        "RKN-chan keeps glancing over nervously",
        "The TSPU box thinks it's ready. It isn't",
        "Tambourine tuned, magic numbers sharpened",
        "Stormtrooper RX-78 takes up his post",
        "Zapret-chan: «Pick a target»",
        "RKN-chan: «Just you try». We will",
        "Lockpicks laid out by size",
        "Zapret-chan loosens her wrists",
        "The black boxes don't know what's coming",
        "The honey badger cracks its neck",
        "RKN-chan checks the locks",
        "Zapret-chan browses the catalogue of tricks",
        "The TSPU box pretends to be impregnable",
        "Honestly first, cunningly after",
        "Zapret-chan ties her hair back",
        "RKN-chan toys with her handcuffs",
        "Grandpa's tricks are in the kit too",
        "Zapret-chan winks: «We'll manage»",
        "Stormtrooper RX-78 adjusts his helmet",
        "The badger sniffs the air: smells like a bypass",
        "RKN-chan: «This internet fears me»",
        "Zapret-chan: «But not me»",
        "The spicy hex values await their hour",
        "The TSPU box has no idea of the scale",
        "Zapret-chan pulls her gloves up to the elbow",
        "RKN-chan draws the curtains",
        "Every hit gets rechecked three times",
        "Zapret-chan pats the honey badger's shoulder",
        "Where there's a target, there's a way",
    ),
    "scan_found": (
        "RKN-chan stamps her foot",
        "Zapret-chan beams and takes a bow",
        "The TSPU box hums resentfully",
        "The honey badger does a victory dance",
        "Stormtrooper RX-78 writes a report",
        "Zapret-chan: «How do you like that?»",
        "RKN-chan: «Not fair!» It is",
        "Platinum trophy unlocked",
        "You can put the tambourine away",
        "Zapret-chan blows the TSPU box a kiss",
        "The black boxes are baffled",
        "Checked three times, not a fluke",
        "RKN-chan dropped her handcuffs",
        "Zapret-chan twirls on the spot",
        "TSPU box: «How?»",
        "The honey badger allows a scratch",
        "The magic numbers lined up",
        "RKN-chan sulks in silence",
        "Zapret-chan pumps her fist",
        "Stormtrooper RX-78 doffs his helmet in respect",
        "What a twist",
        "Zapret-chan: «Go on, apply it»",
        "RKN-chan demands a rematch",
        "Neatly done, if we say so ourselves",
        "Zapret-chan straightens her crown",
        "The TSPU box overheats from the insult",
        "The honey badger is proud. Of itself",
        "RKN-chan: «I'll get even»",
        "Zapret-chan gift-wraps the strategy",
        "The peephole became a window",
    ),
    "scan_open": (
        "RKN-chan: «See, it wasn't me!»",
        "Zapret-chan blinks in surprise",
        "The TSPU box blinks innocently",
        "The honey badger sharpened claws for nothing",
        "Stormtrooper RX-78 detained no one",
        "Zapret-chan: «I was just getting started»",
        "RKN-chan lifts her chin",
        "Nothing to bypass",
        "The tambourine wasn't needed",
        "Zapret-chan puts the lockpicks away",
        "The black boxes aren't to blame here",
        "The door wasn't locked",
        "RKN-chan expects an apology",
        "Zapret-chan: «Well, it happens»",
        "TSPU box: «I hadn't even started»",
        "The honey badger is a bit disappointed",
        "No need to break down an open door",
        "RKN-chan sips her tea pointedly",
        "Zapret-chan will check DNS and the browser",
        "The strategies are resting",
        "Stormtrooper RX-78 has a clean record",
        "Zapret-chan yawns",
        "RKN-chan: «And you blamed me»",
        "It was only a drill",
        "Zapret-chan packs the tricks back",
        "The TSPU box makes an offended face",
        "The honey badger goes back to sleep",
        "RKN-chan smooths her bow",
        "Zapret-chan: «Look elsewhere»",
        "The site managed by itself",
    ),
    "scan_not_found": (
        "RKN-chan smiles smugly. Too early",
        "Zapret-chan bites her lip",
        "The TSPU box is on form today",
        "The honey badger growls but doesn't quit",
        "Stormtrooper RX-78 holds the line",
        "Zapret-chan: «The night is young»",
        "RKN-chan: «I did warn you»",
        "The tambourine wants new rhythms",
        "«All alts are red» — sounds familiar",
        "Zapret-chan keeps turning the catalogue",
        "The black box is tough today",
        "The key word is «yet»",
        "RKN-chan spins handcuffs on her finger",
        "Zapret-chan takes another set",
        "The TSPU box catches its breath. Briefly",
        "The honey badger sharpens claws afresh",
        "The cactus isn't finished yet",
        "RKN-chan is celebrating prematurely",
        "Zapret-chan isn't the giving-up kind",
        "Did they change the TSPU settings again?",
        "Stormtrooper RX-78 sweated but stood",
        "Zapret-chan: «Let's try another way»",
        "RKN-chan admires herself in a pocket mirror",
        "Didn't fit, so not the one",
        "Zapret-chan furrows her brows",
        "The TSPU box relaxed too early",
        "The badger is unimpressed and stubborn",
        "RKN-chan: «Giving up?» No",
        "Zapret-chan knows more ways",
        "Happiness is postponed",
    ),
    "scan_no_internet": (
        "Zapret-chan looks for it under the desk",
        "RKN-chan: «Not me!» This time we believe her",
        "The TSPU box isn't involved. Probably",
        "The honey badger sniffs the cable",
        "Stormtrooper RX-78 spreads his hands",
        "Router, blink twice",
        "Zapret-chan: «No network, no bypass»",
        "RKN-chan is just as surprised",
        "Nothing to bypass: there's no network",
        "Zapret-chan tugs at the cable",
        "The black boxes miss the traffic",
        "Did the cat sit on the router?",
        "RKN-chan peeks behind the wardrobe",
        "Zapret-chan knocks on the router",
        "TSPU box: «Nothing to throttle»",
        "The honey badger goes to check the socket",
        "Did we drop everything?",
        "RKN-chan: «I only blinked»",
        "Zapret-chan will wait for it to return",
        "The window slammed shut",
        "Stormtrooper RX-78 guards an empty wire",
        "Zapret-chan counts the Wi-Fi bars",
        "RKN-chan turns up her palms",
        "The ping left and never came back",
        "Zapret-chan: «It returns, we continue»",
        "The TSPU box is standing idle",
        "The honey badger calls the internet by name",
        "Is RKN-chan hiding scissors?",
        "Zapret-chan puts the search on pause",
        "Let's get the network back first",
    ),
    "scan_address_block": (
        "Zapret-chan lowers her lockpicks",
        "RKN-chan locked the whole address",
        "The TSPU box shut the street, not the door",
        "The honey badger ran into a wall",
        "Stormtrooper RX-78 blocked the road",
        "This needs a detour, not a lockpick",
        "Zapret-chan: «That's beyond my trade»",
        "RKN-chan is pleased with herself",
        "Carpet blocking, no less",
        "Zapret-chan puts the tambourine away",
        "A black box hung a barn padlock",
        "The address is closed entirely",
        "RKN-chan: «No way through here»",
        "Zapret-chan looks for a way around",
        "The TSPU box lowered a barrier",
        "The badger scratches the wall. It's thick",
        "Disguise won't help: the address is shut",
        "RKN-chan folds her arms",
        "Zapret-chan: «We need another route»",
        "They block the address, not the name",
        "Stormtrooper RX-78 lets no one pass",
        "Zapret-chan honestly admits the limit",
        "RKN-chan cracks her whip in triumph",
        "This calls for «three magic letters»",
        "Zapret-chan rubs the bridge of her nose",
        "The TSPU box would fold its arms, if it had any",
        "The badger nods at the wall with respect",
        "RKN-chan: «Just like that»",
        "Zapret-chan doesn't promise the impossible",
        "Only another path will help here",
    ),
    "scan_dns_stub": (
        "Zapret-chan: «DNS first, strategies after»",
        "RKN-chan swapped the nameplate",
        "The TSPU box handed over the wrong address",
        "The honey badger came to the wrong house",
        "Stormtrooper RX-78 turned the signpost",
        "The address leads to a block page",
        "Zapret-chan brings encrypted DNS",
        "RKN-chan: «An address like any other»",
        "The strategies knock on the wrong door",
        "Zapret-chan takes out a loupe and DoH",
        "A black box mixed up addresses on purpose",
        "It was DNS. Again",
        "RKN-chan hides a pencil behind her back",
        "Zapret-chan: «Fixing the directory»",
        "The TSPU box paints new nameplates",
        "The honey badger growls at the signpost",
        "Too early to search: the address is fake",
        "RKN-chan smiles far too innocently",
        "Zapret-chan knows where to enable DoH",
        "Wrong road, wrong destination",
        "Stormtrooper RX-78 waves the other way",
        "Zapret-chan crosses out the foreign address",
        "RKN-chan: «Does it matter where?»",
        "The letter went to the wrong address",
        "Zapret-chan's diagnosis: DNS",
        "The TSPU box poses as the help desk",
        "The badger demands the real address",
        "RKN-chan doctored a digit",
        "Zapret-chan: «We treat DNS first»",
        "Enable encrypted DNS and run again",
    ),
    "scan_unresolved": (
        "Zapret-chan flips the directory. Empty",
        "RKN-chan: «Never heard of it»",
        "The TSPU box says nothing about the address",
        "The honey badger doesn't know where to go",
        "Stormtrooper RX-78 hid the signpost",
        "The help desk doesn't answer",
        "Zapret-chan: «Where do I even knock?»",
        "Did RKN-chan tear out a page?",
        "Address unknown, nowhere to go",
        "Zapret-chan asks the help desk again",
        "The black boxes give no hints",
        "No address, no search",
        "RKN-chan gives a little shrug",
        "Zapret-chan checks for a typo",
        "TSPU box: «I won't tell»",
        "The honey badger walks in circles",
        "The navigator lost its signal",
        "RKN-chan hides the directory",
        "Zapret-chan rings another help desk",
        "There's a target but no address",
        "Stormtrooper RX-78 is «not from around here»",
        "Zapret-chan: «Is that really the name?»",
        "RKN-chan hums a little song",
        "A house without a number",
        "Zapret-chan scratches behind her ear with a pencil",
        "The TSPU box pretends it misheard",
        "The badger sniffs for a trail. There is none",
        "RKN-chan: «Maybe it doesn't exist»",
        "Zapret-chan doesn't buy it and rechecks",
        "Check the name and your DNS",
    ),
    "scan_winws": (
        "Zapret-chan turns the ignition key",
        "RKN-chan watches with interest",
        "The TSPU box needn't worry yet",
        "The honey badger pushes the engine from behind",
        "Stormtrooper RX-78 giggles into his helmet",
        "The engine sneezed and went quiet",
        "Zapret-chan: «Come on, start»",
        "RKN-chan: «Oh, how awkward»",
        "No engine, no search",
        "Zapret-chan pops the hood",
        "The black boxes lie low",
        "What happened is written below",
        "RKN-chan hands over a spanner. The wrong one",
        "Zapret-chan got oil on herself",
        "The TSPU box rubs its paws. Too early",
        "The honey badger growls at the hood",
        "The motor won't catch",
        "RKN-chan hides a snicker",
        "Zapret-chan checks the spark plugs",
        "A tambourine won't help here. Or will it?",
        "Stormtrooper RX-78 is taking bets",
        "Zapret-chan: «I'll deal with you now»",
        "RKN-chan swings her foot",
        "The engine is silent",
        "Zapret-chan reads what the engine wrote",
        "The TSPU box exhaled, wrongly",
        "The badger doesn't quit and keeps pushing",
        "RKN-chan: «Maybe it's for the best?» No",
        "Zapret-chan will find the cause",
        "Have a look at the details below",
    ),
    "scan_network_lost": (
        "Zapret-chan froze with a lockpick in hand",
        "RKN-chan: «It wasn't me, honest»",
        "The TSPU box didn't get to do anything",
        "The badger looks around: where did it all go?",
        "Stormtrooper RX-78 is confused too",
        "Right at the best moment",
        "Zapret-chan: «Hey, give the network back»",
        "RKN-chan blinks",
        "The search is hanging in mid-air",
        "Zapret-chan shakes the router",
        "The black boxes are left with nothing to do",
        "The lights went out mid-play",
        "RKN-chan: «I only sneezed»",
        "Zapret-chan slips in a bookmark",
        "TSPU box: «Not me». Possibly",
        "The honey badger guards the spot we stopped at",
        "Packets left and didn't return",
        "RKN-chan hides scissors behind her back",
        "Zapret-chan will wait for the network",
        "The internet stepped out for air",
        "Stormtrooper RX-78 shines a torch into the wire",
        "Zapret-chan noted where we stopped",
        "RKN-chan raises a surprised eyebrow",
        "Someone chewed through the cable. Oops",
        "Zapret-chan: «We continue when it's back»",
        "The TSPU box is bored without packets",
        "The honey badger calls the network back",
        "RKN-chan puts on an innocent face",
        "Zapret-chan keeps her spirits up",
        "When the network returns, we continue",
    ),
}

__all__ = ["EN"]
