"""Английские весёлые фразы для экранов проверок (см. ``fun_texts.py``)."""

from __future__ import annotations

EN: dict[str, tuple[str, ...]] = {
    "scan_network": (
        "Checking there is internet at all… just in case",
        "«Is the internet on?» The router blinks. Nobody knows what it means",
        "Breaking news: the web is still there. We checked. Twice",
        "RKN-chan is on a lunch break, so we ping the whole internet fast",
        "A tiny packet leaves home and prays the world is still open",
        "Router lights blink in Morse. Translation: «please don't ask»",
        "Poking the web with a long stick from a safe distance",
        "The TSPU box opens one eye at our ping: «Boring. Carry on»",
        "Waiting for a cat video to load, strictly for science",
        "Honey badger rule #1: before fighting the wall, find the road",
        "«Wish you were here,» we write on a postcard to Wikipedia",
        "Hello, internet? It's us. Do you have a minute?",
        "Weather report: partly cloudy, with scattered timeouts",
        "One ping to the news, one ping to the mail, one ping to mum",
        "Counting Wi-Fi bars like sheep. Falling asleep at three",
        "Rehearsing before the show: «Hello, world!» times five",
        "One does not simply start a strategy search without a ping",
        "Our packet asks the cable: «Are we there yet?»",
        "ISP hotline says «your call is important». We ping on our own",
        "If a site opens in the forest and nobody reloads it, does it exist?",
        "Unplug, replug, whisper kind words. The ancient IT ritual",
        "Even the DPI doorman should let a plain ping through. Should",
        "Philosophers on standby: we are proving the internet exists",
        "Lighting a small candle to the Wi-Fi spirits",
        "The internet is a series of tubes. Inspecting the tubes",
        "Local packet reaches Google and asks for an autograph",
        "Google, Wikipedia and a weather page, please wave back",
        "Borrowing moral support from the neighbours' Wi-Fi. Kidding",
        "A bored packet counts hops to the nearest news site. Seven so far",
        "RKN-chan's registry has a million lines. We ping the boring ones",
        "Plumber honey badger taps on the pipes and nods wisely",
        "Pre-flight check: wings, engine, any website at all",
        "Testing the line like a melon: a gentle tap, then listening",
        "Snack break for the TSPU box. It chews, we ping",
        "«Page loading…» The longest-running play in history",
        "Dialling the web: press 1 for news, press 2 for search…",
        "Before a heist you check the street. We check the street",
        "Our packet read the registry for fun and now it is very polite",
        "Reading the internet's temperature with a cold thermometer",
        "First we find out if there is an internet. Then we argue with it",
        "Blink twice if the internet is inside",
        "No tricks, no engines, just one polite ping and a deep breath",
        "A yawning TSPU box inspects a harmless request: «Move along»",
        "Kettle boils, router blinks, the web wakes up",
        "Tuning the antenna. Metaphorically. We have no antenna",
        "Mapping the road before the convoy. The convoy is shy",
        "Putting on a tie for the packet's first date with the internet",
        "Hunting for the little offline dinosaur. Hoping it stays hidden",
        "Even if RKN-chan is watching, a ping is just a ping",
        "The packet signs the guest book at the front desk of the web",
        "Whispering «hello» to the biggest room in the world",
    ),
    "scan_baseline": (
        "Trying the site directly, no tricks…",
        "Politely asking the ISP: «May we?»",
        "Walking up to the site in plain clothes. The doorman squints",
        "No hat, no moustache, no tricks. The packet feels naked",
        "RKN-chan licks her stamp… and we knock anyway",
        "«Nothing to declare,» says the packet, sweating a little",
        "TSPU box looks up from its crossword: «Hm? Oh, go ahead»",
        "Honey badger sits this round out. For science",
        "Asking for the homepage with a perfectly straight face",
        "Seeing what the ISP does when we simply ask",
        "«Good evening, may I have one webpage, please?»",
        "The registry says maybe. The packet says please",
        "Baseline run: the before photo for the before-and-after",
        "«Who goes there?» asks RKN-chan. «Just me,» says the packet",
        "DPI doorman asks for our badge. We have none. Awkward",
        "Reading the site's mood before getting clever",
        "First try, zero cleverness. The badger is bored already",
        "Step one of any heist: walk in normally and see who stops you",
        "If the site opens right away, we are going to lunch",
        "Watching the page load like watching a kettle",
        "Knock knock. «Who's there?» «A completely ordinary packet»",
        "Our packet strolls past the doorman, whistling innocently",
        "Does the DPI doorman ever blink? Walking past to find out",
        "Sneaking is for later. Right now we simply ask",
        "Browsing like grandma did, no cleverness at all",
        "Hello, site! It's me, a totally unmodified packet",
        "Fair fight: one plain request versus whatever stands in the way",
        "Stage one: ask nicely. Stage two: get creative",
        "Without winws2 it feels draughty out here",
        "Honest face on, hands visible, nothing in the sleeves",
        "The ISP gets a fair chance to wave us through",
        "A packet with a clean conscience queues at the border",
        "Letting the network do whatever it does to polite requests",
        "Headline: «Packet tries the front door, to everyone's surprise»",
        "Does the front door have a bouncer, a doormat, or neither?",
        "TSPU box: «Name, purpose of visit?» Packet: «Reading»",
        "Hiding, blocked, or just slow? Asking without tricks",
        "One plain request, served without sauce",
        "Zero tricks. The honey badger yawns and checks the time",
        "The packet rings the bell and stands there holding flowers",
        "RKN-chan checks her list twice, then goes back to her tea",
        "Plain handshake, plain face, plain fingers crossed",
        "Testing the road before we pack the tunnelling gear",
        "Showing up unannounced, like polite relatives",
        "DPI squints at the request. The request squints back",
        "It's called a control test. It's also called minding our manners",
        "Unarmed, unmasked and mildly nervous: round one",
        "Calling the site on the landline, no apps",
        "Shortest road, longest suspense",
        "Our shy packet steps into the spotlight, no costume",
        "Is the wall really there? Looking before we climb it",
    ),
    "scan_control": (
        "Firing winws2 with blanks: is it magic by itself?",
        "winws2 runs with an empty strategy: a car with the handbrake on",
        "Control test: engine on, strategy off, white coat on",
        "The engine purrs, does absolutely nothing, and gets paid for it",
        "Honey badger naps on the hood of the idling engine",
        "If winws2 alone fixes everything, we are calling a priest",
        "Owning a hammer doesn't build a house. Checking that for sure",
        "A stage with lights on and no actors. Yes, on purpose",
        "TSPU box eyes the idle winws2: «Nothing to see? Fine»",
        "«Suspiciously quiet,» notes RKN-chan. That's the plan",
        "«Worn-out servers,» says the TSPU box. Our idle engine takes notes",
        "winws2 pretends to be busy, like all of us on Monday",
        "Dry run: wardrobe full of costumes, nobody wearing them",
        "Idling at the red light so the green one feels earned",
        "Does winws2 change anything by merely existing? Asking nicely",
        "Turning the key but not touching the gas",
        "Neutral gear. The doorman sees nothing new, hopefully",
        "Nothing up our sleeves. Nothing in them either",
        "Warming up like a car on a frosty morning",
        "Calibrating the scales: put nothing on, see what they say",
        "Pressing «Start» and then, bravely, nothing else",
        "«Do something!» pokes the badger. «Not yet,» says winws2",
        "Quietest mode in the manual, page one",
        "Scientists call it a control. We call it winws2 on holiday",
        "Will a TSPU box notice an engine that does nothing? Testing",
        "Engine idling like a taxi driver waiting for a fare",
        "Spy engine in civilian clothes today",
        "Neutral drive: smooth, quiet, mildly suspicious",
        "Lazy Sunday for the bypass engine",
        "Only test where laziness is a feature",
        "Empty to-do list, full cup of tea, winws2 reporting for duty",
        "Checking the baseline of the baseline. Yes, we are that thorough",
        "Empty strategy, full of promise. Mostly empty though",
        "«Give me a trick,» whispers the engine. «Not yet,» we say",
        "RKN-chan finds nothing to stamp on a silent engine",
        "A tiny packet rides the empty bus. So much legroom",
        "If this works on its own, the engine gets a medal",
        "Spinning the wheels with the car on a jack",
        "Orchestra tunes up and then politely sits in silence",
        "Rowing with the oars out of the water. Fair comparison later",
        "Plugging in the hammer and leaving it on the shelf",
        "Hands in pockets, whistling, looking at the clouds",
        "DPI doorman watches winws2 loiter and writes nothing down",
        "Lights on, music off: the null experiment",
        "A cat on the keyboard would be about as tricky as this run",
        "An empty strategy walks into a bar. Nothing happens",
        "Fake news: «Engine saves internet by doing nothing». Verifying",
        "Giving the ISP a very boring thing to look at",
        "RKN-chan checks the engine for magic. Finds only a spinning fan",
        "ISP and DPI watch an engine that does nothing. Riveting television",
        "Zero tricks on the clock and the badger asks for a snack",
    ),
    "fake": (
        "Handing DPI a decoy letter while the real one sneaks past…",
        "Sending a stunt double ahead of the real packet",
        "DPI doorman reads a forged postcard as the real one tiptoes by",
        "Cardboard cutout of a request stands in for the real thing",
        "Rubber duck placed in front of the security camera",
        "Decoy goes first and soaks up all the attention",
        "This fake packet dies on the way. A noble sacrifice",
        "Dummy on the doorstep keeps the watchman busy",
        "Server will ignore this one. DPI will frame it and hang it",
        "Decoy with a short fuse (low TTL) volunteers for duty",
        "TSPU box examines the decoy with enormous seriousness",
        "RKN-chan stamps the fake «BLOCKED» and goes for tea",
        "Note that will never arrive. It knows. It goes anyway",
        "Packet built to expire halfway to the server. Tragic, brief",
        "Fake in a tuxedo, real one in slippers. Guess who gets stopped",
        "Mirage rolls out in front of the real traffic",
        "Forged page lands in the DPI's inbox. No reply needed",
        "Fake hello for the inspector, real hello for the server",
        "Deliberately bad checksum. Cheeky, and a little rude",
        "Convincing nonsense, served to DPI on a silver plate",
        "False clue for the detective, true message for the server",
        "Waving a flag on the left, walking out on the right",
        "Honey badger throws a fake and slips through the hedge",
        "Stand-in takes the questions; the real packet takes the road",
        "Distraction by fake ID: «Born in 1900, don't ask»",
        "Sacrificial packet volunteers to go first. Brave little guy",
        "Believable fib, packet-sized",
        "Prank packet nobody at the server will ever read",
        "Inspector got a fake. The server will politely ignore it",
        "Dummy shot to draw the guard's eye",
        "Look-alike takes the heat and vanishes into thin air",
        "Writing DPI a letter that nobody will answer",
        "Mannequin in the window keeps the watchman busy",
        "First the fake, then the real, and DPI has already moved on",
        "Just wrong enough to be ignored: the art of the fake",
        "Cheerful impostor travels ahead of the true message",
        "Showing the guard an empty envelope. Very official-looking",
        "Shiny object for the lookout to stare at",
        "RKN-chan wanted the real packet. She got a very good drawing",
        "TSPU box: «Look, a request!» The real one: «Not me»",
        "Acting its heart out: an Oscar-worthy decoy, for a packet",
        "Plan: DPI watches the left hand. The right hand is a packet",
        "Honey badger hires a body double. The double charges extra",
        "News from the packet desk: the real one is already home",
        "Moustache on, passport expired: the perfect stand-in",
        "Magician's rule: look at the fake while the real one vanishes",
        "ISP kindly carries a decoy it will never understand",
        "Paper planes worked for Telegram in 2018. Now: paper packets",
        "«Got you!» says DPI. «Got me,» agrees the decoy",
        "A paper plane flies at the DPI window. Pure distraction",
        "Fake with all the paperwork except a valid destination",
    ),
    "split": (
        "Slicing the hello into neat little pieces…",
        "Slicing the packet so thin the TSPU box asks for a magnifier",
        "Bite-sized greeting for a picky DPI",
        "Hello so finely chopped the doorman needs new glasses",
        "Packet through the paper cutter: out comes confetti",
        "Splitting the hello in the middle of a word. Servers are patient",
        "Two half-sandwiches out of one whole. DPI eyes only one half",
        "Cutting the TLS hello like salami: thin, even, and fast",
        "Server gets the whole story. DPI gets a fragment",
        "Chocolate bar rules: squares for everyone, no one sees the wrapper",
        "Giving DPI half a sentence and keeping the rest",
        "«Show me the whole message,» says RKN-chan. «Only in pieces»",
        "First packet chopped into puzzle pieces",
        "Greeting served in tapas-sized portions",
        "Just a thin slice off the front, nobody will notice",
        "Hello arrives in instalments, like a TV series",
        "Knife, packet and one very careful cut",
        "Hello, in two shifts. DPI only catches the early one",
        "Trimming the packet right where the site name lives",
        "Honey badger tears the packet in two. Calmly",
        "Ribbon-cutting ceremony for a TLS hello",
        "Greeting breaks like a cookie, crumbs and all",
        "Splitting hairs. And packets. Mostly packets",
        "Story in two parts, with an awkward pause between",
        "Pulling the packet apart like string cheese",
        "DPI reads the first half and only the first half",
        "The hello comes in pieces. The server brought glue",
        "Snipping with tiny scissors, tongue sticking out",
        "A jigsaw puzzle delivered instead of a picture",
        "Cut exactly where the site name begins. Surgeons are jealous",
        "No single piece says too much. That is the whole idea",
        "Pieces handed out like party favours",
        "Cut here, along the dotted line",
        "Bread knife out, packet on the board",
        "A slice for DPI, a slice for the server",
        "A long note cut into postcards",
        "Chopping without a recipe, just by feeling",
        "Sisters on a trip: the pieces travel separately",
        "Cutting a TLS hello is like cutting hair: position matters",
        "Experimenting with where exactly to cut",
        "Two pieces, three pieces, or a whole salad of them",
        "The TSPU box reads the first slice and gets only «Hel»",
        "«Where's the rest?» asks the doorman. «Coming. Eventually»",
        "Local packet cut in half, reports feeling great",
        "RKN-chan wanted a full hello. She got the first syllable",
        "TLS hello arrives in a bento box",
        "Pieces queue politely, like at the post office",
        "So fine that even the registry loses the line",
        "The packet asks the badger to be gentle with the knife",
        "ISP receives a loaf of bread, one slice at a time",
        "Packet origami: fold here, cut there, ship",
        "Cutting the greeting where the censors' favourite word sits",
    ),
    "disorder": (
        "Shuffling packets like a deck of cards…",
        "End of the story arrives first. DPI doorman hates spoilers",
        "Playing the song backwards. The server hums along anyway",
        "Swapping the order like a magician with a card trick",
        "Second half arrives before the first. Tidy chaos",
        "Puzzle on a shaky table, mixed by accident (not an accident)",
        "Pieces arrive in reverse, the server sorts them out",
        "Delivery, back to front",
        "Pieces fall out of the bag in a random order",
        "Last piece cuts in line and nobody complains",
        "Flipping the sequence like a pancake",
        "Queue that goes the wrong way, on purpose",
        "A story that starts from the ending",
        "TSPU box expects page one. Gets page two. Panics politely",
        "RKN-chan reads the book from the last page, like a mystery",
        "Packets line up in reverse, politely",
        "Order of arrival scrambled, within reason",
        "Turning the order upside down like an hourglass",
        "A little shuffle: the tail comes before the head",
        "Guests seated in the wrong order, they find their places",
        "Leapfrog with packet pieces",
        "Fragments on the conveyor belt, going the wrong way",
        "The honey badger enters by the exit, as usual",
        "Two neighbours in the queue swap places",
        "Traffic jam on purpose, in a very organised way",
        "Wild but deliberate order",
        "Dominoes mixed before they fall",
        "Dealing the second card first. Poker face on",
        "Nobody said the parts had to arrive in order",
        "Envelopes arrive in the wrong order, the letter is intact",
        "Tail first, head later. Like a lizard in a hurry",
        "Spinning the order like a roulette wheel",
        "Out-of-order delivery: the DPI doorman's least favourite pastime",
        "Packets race to the finish line",
        "The second fragment overtakes the first. Rude but legal",
        "Backwards parcels: unusual, but perfectly legal",
        "Tangled thread; only the server can untangle it",
        "Jumbled pages. Luckily the server has page numbers",
        "Everyone leaves the bus through the back door today",
        "Can DPI follow a story told out of order? Let's see",
        "Shaking the box before the pieces slide out",
        "Finale before the opening act. Critics are confused",
        "Musical chairs for packets. The music is chaotic",
        "«I got the ending first,» says the doorman. «Is that bad?»",
        "A queue where the VIP guest stands at the back for once",
        "Fake news: packets arrived in order. Reality: not even close",
        "ISP hands over the pieces in an order only the server understands",
        "«Do I really have to go second?» asks a tiny nervous packet",
        "The registry says «page 1, page 2». The packets say «lol»",
        "Slideshow in the wrong order: nobody gets the joke, except the server",
        "TSPU box blames worn-out servers for the mess. It's us, actually",
        "Zebra crossing for packets: the last one runs first",
    ),
    "syndata": (
        "Hiding a note right in the handshake…",
        "Handshake with a note in the palm. DPI suspects nothing",
        "SYN packet leaves home with a tiny backpack. Nobody asked",
        "«Please sign for this parcel,» says the very first packet",
        "TSPU box expects an empty SYN lunch box. Surprise: a sandwich",
        "Whispering secrets before saying hello: very rude, very effective",
        "RKN-chan checks the SYN for contraband and finds a crumb",
        "Smuggling bytes in the handshake, the least suspicious place",
        "Honey badger hides snacks in the handshake. Old habit",
        "«SYN packets are always empty,» said no one who has met us",
        "Knock on the door arrives with a postscript",
        "Data hops on the handshake like a stowaway on a ferry",
        "Hello with luggage: arrives early, leaves nothing behind",
        "The oldest trick in the book, with a fresh coat of paint",
        "Nervous packet clutches a note and tries to look empty",
        "A knock-knock joke where the punchline is already inside",
        "Putting a toy surprise in the first packet, like in cereal",
        "The ISP waves through an «empty» SYN. It was not empty",
        "Fake news: «Handshakes carry no data». The local packet disagrees",
        "Starting the conversation with the second sentence",
        "Server unwraps the handshake and finds a bonus",
        "DPI doorman checks the front door; the note sits in the doormat",
        "Early bird packet brings the worm before the greeting",
        "Handshake so firm it squeezed a few bytes out",
        "Cramming data into step one, like the last suitcase before a trip",
        "Skipping the small talk and passing the note",
        "Side quest attached to the SYN",
        "Is that an empty SYN? Look closer. No, closer. Okay, don't",
        "TSPU box studied empty handshakes. Today's exam is different",
        "Bribing the handshake with a tiny parcel",
        "Shaking hands with a folded paper inside the palm",
        "«You sent data in a SYN?» «Surprise!»",
        "Giving the first packet a pocket and a purpose",
        "This handshake ends with an unexpected plot twist",
        "Doorbell rings, and it's already carrying a letter",
        "Shortest letter in history, delivered with the first packet",
        "«Dear server, P.S. I brought something»",
        "Opening move: pass the note before the introductions",
        "RKN-chan counts handshake steps on her fingers and loses count",
        "One packet, two jobs: knock and deliver",
        "Hiding in the handshake, because nobody checks the handshake",
        "The packet shows ID, a smile and a hidden pocket",
        "Secret ingredient in the first step. Chefs would be proud",
        "Small talk replaced with a smuggled parcel",
        "Doorman wants the whole story. We started with the footnote",
        "Surprise attachment on the very first packet",
        "SYN-sational delivery: data arrives before it is invited",
        "DPI watches the handshake like a hawk. The hawk blinks",
        "A tiny nervous packet whispers its message into the handshake",
        "ISP sees a knock. TSPU box sees a knock. Neither sees the note",
        "Bold move: serving dessert before the greeting",
    ),
    "oob": (
        "Sending a packet through the back door…",
        "One tiny byte yells «URGENT!» and skips the whole queue",
        "Out-of-band: the VIP entrance for exactly one byte",
        "Priority ticket for a very small passenger",
        "TSPU box checks the front door; the byte takes the cat flap",
        "RKN-chan guards the main road. The byte hikes through the woods",
        "Waving the urgent flag, just to see who looks",
        "An ambulance siren on a single byte. Please clear the road",
        "Fire-alarm sticker on a perfectly harmless packet",
        "Urgent pointer points somewhere. Nobody knows where, itself included",
        "Mailman confused: this letter says «read me first» in crayon",
        "Note passed under the desk during the lecture: very urgent",
        "Honey badger takes the staff stairs. Elevators are for amateurs",
        "Whispering «psst» through the side window",
        "DPI reads the main road, we take the footpath",
        "Hot potato byte, passed on out of turn",
        "«There's a queue!» says the doorman. «I know a guy,» says the byte",
        "Interrupting the conversation with one very small shout",
        "Flashing light on a single character. Disco byte",
        "Emergency exit, used for non-emergency purposes",
        "Out of the band, into the spotlight",
        "Express lane for a one-byte parcel",
        "Tossing a note over the fence, like a neighbour with a ball",
        "The server hears «Urgent!» and puts its coffee down",
        "One byte, one siren, zero explanations",
        "ISP's queue is fair. This byte pretends to be a VIP",
        "Secret passage behind the bookshelf, now with a labelled door",
        "Flag raised over a character of no particular importance",
        "Fake news: «Byte rushes to hospital». It's fine, it just likes sirens",
        "Mixing urgent and non-urgent: confusing doormen since forever",
        "A tiny nervous packet shouts «URGENT!» and then hides",
        "Urgent flag: a sticker that makes everyone slightly nervous",
        "Scooting past the guard on an express scooter",
        "Byte jumps the queue and says it was always there",
        "TSPU box expected a normal queue. The byte brought a jetpack",
        "Back-alley delivery service delivers exactly one byte",
        "Dropping an urgent postcard into a regular mailbox",
        "Priority lane, population: one",
        "Sending a side message while the main one waits patiently",
        "Alarm bells for one byte, while DPI still reads the main page",
        "The pointer says «look here!» The doorman looks elsewhere",
        "Squeezing through the revolving door in the wrong direction",
        "Treating one lucky byte like a celebrity",
        "A courier on a bicycle takes the side street",
        "Skipping the line like someone who knows the manager",
        "Server perks up at «urgent». DPI hasn't heard of it",
        "Calling it out-of-band sounds cool. Mostly it's a rude cough",
        "A one-byte side quest, accepted by the server",
        "Whistling innocently and pushing the urgent button",
        "Carrying a fire-alarm sticker into a library",
    ),
    "seqovl": (
        "Overlapping packets like roof tiles…",
        "Scribbling cat doodles over the real text, very professionally",
        "Junk on top, secret below: a lasagne with trust issues",
        "TSPU box reads the top note: «Cat recipes». Underneath: the request",
        "RKN-chan reads the top layer and nods. The rest is for the server",
        "Pancake stack of sequence numbers. The syrup is junk",
        "Writing «lorem ipsum» over the real sentence",
        "The server reads the real line, DPI reads the doodles",
        "Sticky note of gibberish over the important part",
        "Two stories on one line: one real, one for show",
        "Palimpsest, but make it packets",
        "Honey badger buries the treasure under leaves",
        "Packets share a few bytes, as good neighbours share sugar",
        "Sequence numbers collide. Nobody is hurt, DPI is confused",
        "DPI sees page one. The server sees page one with a hidden page",
        "Overwriting the first bytes with confetti",
        "A decoy layer exactly where DPI loves to read",
        "Putting a fake cover on a real book",
        "The message hides in plain sight, behind a scribble",
        "Projector slides stacked on top of each other. Which one is real?",
        "Doorman and server read the same bytes and disagree",
        "Folding the packet like a napkin at a fancy restaurant",
        "Hide-and-seek where the hiding place is a pile of junk",
        "Fresh paint on the wall, the real wall behind it",
        "Sequence numbers overlap on purpose, like carpet and rug",
        "Burying the hello in noise, shovel by shovel",
        "Junk bytes: not just trash, a protective coat",
        "Moustache drawn on the portrait. The portrait doesn't mind",
        "One layer or two? Ask DPI and the server separately",
        "Shingling the data: tile by tile, roof by roof",
        "Lasagne rule: the good stuff is in the middle",
        "Real letter and a fake one on the same sheet",
        "Middle of the packet gets a disguise",
        "Overlap zone: where the server and the DPI box disagree",
        "This packet is wearing a hat made of junk",
        "Fake news: «Sequence numbers never overlap». Ours do. It's fine",
        "A tiny nervous packet hides under its own scribbles",
        "TSPU box: «This text is boring!» It is, on the surface",
        "RKN-chan squints at the page and sees only cat doodles",
        "Stacking bytes like a sandwich with a questionable middle",
        "Cover story, in bytes",
        "Two readers, one page, two different stories",
        "Junk goes first, truth hides in the second layer",
        "Padding with personality",
        "Disguising a page by drawing on it",
        "The oldest cover-up in the book: more paper on top",
        "A layer of snow over footprints",
        "Real text mixed with filler, strictly for the server's eyes",
        "So neatly overlapped that Tetris players applaud",
        "Decorative hello over the decorated hello",
        "Honey badger dismisses the nonsense. The doorman reads it carefully",
    ),
    "hostfake": (
        "Dressing the site name in someone else's clothes…",
        "Telling the DPI doorman we are visiting someone else entirely",
        "Name tag: «Hello, my name is Totally Innocent Site»",
        "TSPU box reads a boring site name and relaxes its shoulders",
        "RKN-chan checks the registry: the fake name isn't on it",
        "Borrowing a famous site's name, with a promise to return it",
        "Stage name for the hostname. The server knows the real one",
        "A fake guest enters first, holding a harmless name",
        "Honey badger puts on a tiny fake moustache",
        "«I'm here for the cooking blog,» says the packet, shifty eyes",
        "Passport with a made-up hostname and a very serious stamp",
        "DPI hears one name, the server reads another",
        "Changing the doorbell label for a few milliseconds",
        "Costume party: the hostname came dressed as someone popular",
        "Ordering coffee under a different name",
        "Swapping the label on the jar while the jam stays the same",
        "The ISP gets a postcard to a friendly site; the real one follows",
        "Nicknames for websites: DPI loves nicknames",
        "Whoever is on the guest list, that is who we are today",
        "Writing a famous domain on the t-shirt and walking in",
        "Decoy host line for the inspector's eyes only",
        "Charades for the doorman: guess the site (wrong on purpose)",
        "Hiding the real name behind a more popular one",
        "«Yes officer, I'm visiting my aunt.» (The aunt is a decoy domain)",
        "Wrong name on purpose, the right one right after",
        "Fake news: «Packet visits popular site». It never did",
        "Boring name goes first, the real name arrives later",
        "Pretending to visit the sunny side of the internet",
        "Disguise kit: one false hostname, no moustache",
        "A tiny nervous packet rehearses its alias in the mirror",
        "Hostname theatre: tonight's lead role is played by a decoy",
        "Introducing ourselves as someone with a spotless record",
        "Fake host, genuine purpose",
        "Inspector reads the visitors' book. Suspiciously confident handwriting",
        "Pasting a made-up domain over the real one",
        "DPI gets a name it likes and goes back to its crossword",
        "Giving the bouncer a name from the guest list",
        "Exchange of name tags at the door; no one checks twice",
        "The doorman salutes the decoy and ignores the real one",
        "Borrowed identity, returned in perfect condition",
        "Alias in the hello, truth in the second line",
        "Safe-looking domain in the greeting, like a polite disguise",
        "TSPU box: «Oh, it's you! Go on in, buddy». It was not us",
        "RKN-chan looks for the site in her list under the wrong name",
        "Name on the envelope and name in the letter disagree",
        "Mistaken identity, by design",
        "Honey badger wears a hat labelled «Not a honey badger»",
        "Request with a stage name and a stage smile",
        "Switching name tags like it's a masquerade",
        "The server sees through it. DPI doesn't. That's the plan",
        "Fake name, real server, awkward but effective introductions",
        "A lookalike domain walks into a bar. DPI buys it a drink",
    ),
    "udp": (
        "Sneaking UDP packets past quietly…",
        "Voice packets learning to blend in with the crowd",
        "QUIC puts on a trench coat and a fake nose",
        "Game packets in plain clothes, pretending to be a screensaver",
        "TSPU box hears a voice call and mutters: «Is that QUIC? Not sure»",
        "RKN-chan wants to block the game lobby. The packet hides in a plant",
        "UDP has no handshake, so we improvise a little",
        "Honey badger joins the voice chat, incognito",
        "Tuning the connection for low-ping heroes",
        "«Can you hear me?» «Yes!» «Great. DPI can't»",
        "Fast, fragile and in disguise: the life of a datagram",
        "Fake noise over the call, like a radio between stations",
        "QUIC as plain background hum, nothing to see",
        "Headset conversation hidden inside a quiet hum",
        "Confetti in front of the QUIC hello",
        "A fake packet before the real QUIC, like a warm-up act",
        "DPI wants to know whether this is a game or a call. Just noise, sir",
        "Padding on a datagram: a tiny sweater for the winter",
        "Teammates stay audible while the box pretends to sleep",
        "Datagrams travelling light: no luggage, no receipt",
        "Video call packets that look like nothing at all",
        "Voice stream wears sunglasses, indoors, at night",
        "Packet lengths tweaked to be less memorable",
        "Kindly messing with the first QUIC packet",
        "No acknowledgements, no regrets",
        "TSPU box listens to UDP like a radio with no stations",
        "Making QUIC look like something dull and municipal",
        "Game traffic wearing a fake moustache",
        "Speaking UDP: short sentences, no manners",
        "The ISP hears the call but not the details",
        "Shouting across the canyon with a megaphone made of noise",
        "Gentle disguise for the fastest packets in town",
        "Giving the lobby music a different genre",
        "Datagrams change costumes between scenes",
        "Fake news: «Voice call vanishes into thin air». It is just shy",
        "A tiny nervous packet is late for the match",
        "Dressing up call audio as small talk",
        "Low ping, high hopes, medium disguise",
        "UDP doesn't wait for anyone, so neither do we",
        "Whisper-quiet UDP, no questions asked",
        "Every datagram gets a new name tag and a new hat",
        "The doorman checks tickets for TCP. UDP sneaks into the stadium",
        "RKN-chan sighs at QUIC: it never sits still",
        "Stage makeup for real-time packets",
        "The honey badger plays a match with its eyes closed",
        "«Not a block, a slowdown,» says the TSPU box of a laggy call",
        "Gentle trick for the speedy stuff",
        "Teaching packets to pretend they're elevator music",
        "Voice and games: two things you do not want to lag",
        "Disguising a squeal as a hum",
        "Pings in costume, ready for the match",
        "Wrapping the call in a plain brown wrapper",
    ),
    "scan_generic": (
        "Trying on the next strategy like a new hat…",
        "Picking locks one by one…",
        "DPI is still holding. We are stubborn",
        "RKN-chan taps her stamp. The honey badger taps the next idea",
        "The TSPU box is on its third coffee. We are on our thirtieth try",
        "«Next!» shouts the honey badger. The strategies queue up nervously",
        "Strategy number whatever. We lost count and that's fine",
        "A fresh strategy walks in, shaking, holding its résumé",
        "Spinning the Wheel of Fortune, packets edition",
        "Rummaging in the bag of tricks for something shiny",
        "Another strategy, another chance",
        "DPI shrugs. We shrug harder",
        "Not every key fits. We have a large keyring",
        "Looking for the crack in the wall, brick by brick",
        "Mixing a new potion from the usual ingredients",
        "Fifty ways to say hello to a firewall. Trying the next one",
        "Tinkering with packets while the kettle boils",
        "«Have you tried turning it off and on?» Yes. Now trying other things",
        "Fake news: «All strategies are the same». They are not. We checked",
        "RKN-chan has a registry. We have a notebook of ideas",
        "Each strategy gets its moment in the sun",
        "Next contestant on Strategy's Got Talent, please",
        "Jiggling the handle in a new way",
        "One more way through the maze, with a flashlight",
        "Packets back in the lab. White coats on",
        "DPI doorman yawns, we try the next outfit",
        "Cycling through ideas faster than a coffee order",
        "A new approach, same stubborn spirit",
        "Tuning like a chef: a pinch of delay, a dash of fake",
        "The honey badger doesn't give up. Neither do we",
        "Poking the problem from a new angle",
        "Patience, one more strategy and a biscuit",
        "TSPU box thinks it has seen everything. Let's see the next trick",
        "Last lock pick was nice. Trying the next one anyway",
        "Ticking ideas off the list like groceries",
        "This strategy was recommended by a very confident packet",
        "Plan B, plan C… we are somewhere around plan Q",
        "ISP watches us try. Popcorn is available",
        "A different handshake with the network",
        "Scanning the strategy book for something we haven't tried",
        "Another tweak, now with 12% more audacity",
        "It's not a bug, it's a strategy that wasn't meant to work. Yet",
        "Moving on to the next one. Nothing personal",
        "«Almost,» says the packet. «Not quite,» says the network. Next!",
        "Twisting the knobs until something clicks",
        "Block, slowdown, «worn-out servers»: many names for one wall",
        "Is this the one? Probably not. Let's see anyway",
        "The list is long, and so is our patience",
        "Reading the strategy menu: today's special is persistence",
        "Running the next experiment, mildly optimistic",
        "Another rabbit out of the hat",
        "Trying a new hat on the same old problem",
    ),
    "scan_found": (
        "Contact! Checking again to be sure…",
        "«Did it just work?» «I think it did.» «Do it again.»",
        "Hold the champagne: the second test is on its way",
        "The TSPU box blinked and we got through. Blink or nap?",
        "RKN-chan sneezed and the block hiccuped. Verifying",
        "The DPI doorman looked away for a second. Did he really?",
        "Honey badger sniffs the find: smells like success, needs a recount",
        "Skill or coincidence? The recheck will tell",
        "Pinch me. No wait, ping me again",
        "One success is an anecdote, two is a pattern. Collecting two",
        "A tiny victory dance, postponed until the recheck",
        "It worked once. Now to see if it can do it on purpose",
        "Please do that again, for the cameras",
        "Strategy gets a second interview. Nervous, but promising",
        "Suspiciously good. Checking again",
        "Opening the door once more to see if it's still open",
        "Fake news: «Strategy works». Awaiting official confirmation",
        "Re-running the check. Trust, but verify",
        "It opened! Let's see if it opens twice",
        "Packet came back smiling. We need a second witness",
        "Good sign! Asking it to do that again",
        "Putting the discovery through a short interrogation",
        "Fingers crossed, toes crossed, tests running",
        "Magnifying glass out. Dramatic music on",
        "Taking the result for a second spin",
        "«It works!» «Show me again.» «It works!» «Once more.»",
        "Cautious optimism with a stopwatch",
        "First success noted. Waiting for an encore",
        "Even the ISP seems to wave us through. Verifying the wave",
        "That could be the one. Or a lucky blink. Checking",
        "Winner gets a proper exam, no cheat sheet",
        "A mirage or an oasis? Walking closer",
        "Not popping the champagne just yet",
        "Lightning strikes twice? Statisticians want to know",
        "The packet reports success and asks us not to tell RKN-chan",
        "TSPU box is scratching its head. We scratch ours too, then retest",
        "Doing a recount, to be sure",
        "Repeating the test so we can trust the result",
        "Careful hands: this one might be precious",
        "Good news is a fragile thing. Double-checking it",
        "Confirming the find, because once might be a fluke",
        "Triple-checking, because the first time felt too easy",
        "Handle with care: promising candidate",
        "We got a bite. Reeling the line in gently",
        "A second gate, a second look",
        "Result looks good; now to prove it isn't a mirage",
        "Will it hold when the doorman is awake? Testing",
        "RKN-chan dozed off on duty. Verifying that the nap is real",
        "Retesting, because first impressions can mislead",
        "It looked easy. That's why we're checking twice",
        "TSPU box: «Slowdown? What slowdown?» The page opens. Rechecking",
        "Waiting for the encore like true fans",
    ),
    "blockcheck": (
        "Knocking on sites: knock-knock, who's there?",
        "Asking every site: «How are you?»",
        "Postman with a very long route: every site on the list",
        "RKN-chan has a registry. We have a checklist. Let's compare notes",
        "TSPU box on duty: «Which site? That one? Hmm, hang on…»",
        "Carpet-blocking drops whole neighbourhoods. Checking who's still home",
        "Roll call for websites: «Present!», or maybe silence",
        "Honey badger inspects the neighbourhood, one doorbell at a time",
        "Asking each site to open up, one by one",
        "The ISP knows the way to every site. We ask whether it takes us",
        "A paper plane for each site on the list. Return flights only",
        "Remember the paper planes? We send ordinary pings instead",
        "Did the block hit innocent neighbours, like t.co once did? Checking",
        "Every site gets a tiny request and a big smile",
        "Sorting sites into those that answer and those that think about it",
        "TSPU box hums «worn-out servers» while we check every site",
        "Checking the chart: open, slow, silent, mysterious",
        "No judgments, just a polite ring on every doorbell",
        "Taking attendance in the great classroom of the web",
        "Peeking through the keyhole of each site",
        "Census of reachable sites, conducted by a very polite packet",
        "The DPI doorman has a list. We have one too",
        "Same knock on every door, different reactions",
        "Report cards for websites: «Opens well», «Needs improvement»",
        "Cloud neighbourhoods get blocked together. We check house by house",
        "If a site goes quiet, we write «shy» and move on",
        "Surveying the web with a clipboard and sensible shoes",
        "Fake news: «All sites reachable». Reality is being checked",
        "Which sites come out to meet us?",
        "A detective with a notebook and a list of suspects (all innocent)",
        "«Not a block, a slowdown,» says the TSPU box. We time it",
        "Gathering evidence in a friendly way",
        "Who answers fast, who answers slow, who doesn't pick up?",
        "Same question for every address",
        "Dropping by a bunch of sites, uninvited but polite",
        "Neighbourhood watch for websites",
        "Listening for echoes from each address",
        "Your friendly local site inspector, no uniform",
        "Ticking each site off the checklist as we go",
        "Honey badger doesn't ring. Honey badger knocks and waits",
        "Long list, short wait for each. Moving along",
        "Even sites hiding in cloud ranges get a polite knock",
        "We know that one site: let's see if it knows us",
        "Asking the sites for a quick sign of life",
        "Taking each site's temperature with a very small thermometer",
        "Filling in the table: site, answer, time",
        "Sampling websites like a food critic",
        "The registry is on her desk; the sites are on our list",
        "Reading the mood of every site on the list",
        "Checking in on every site, as a polite guest",
        "Collecting reactions: smiles, shrugs, silence",
    ),
    "dns": (
        "Comparing addresses with an honest phonebook…",
        "Asking two neighbours and comparing their answers",
        "Phonebook with forged pages? Flipping through carefully",
        "RKN-chan, did you borrow the phonebook again? It has new pages",
        "TSPU box whispers «that site lives here now». Does it, though?",
        "Address book with a suspicious sticker: «Edited by a friend»",
        "Spot the difference: two sets of answers, one magnifying glass",
        "Honey badger sniffs for tampered addresses",
        "Comparing the provider's answer with an honest one",
        "«Where does this live?» asked in two different places",
        "Names that wandered off to the wrong address: wanted",
        "Same question, two witnesses, one possible fib",
        "Was the street sign painted over? Checking",
        "Verifying that the map matches the territory",
        "ISP gives an address, a stranger gives an address: compare",
        "Two dictionaries consulted on one word",
        "Postcodes on all the envelopes: checking each digit",
        "ISP says north, honest resolver says south. Taking notes",
        "DPI doorman likes rewriting guest lists. We read the original",
        "Fake news: «Every address is correct». Checking the news",
        "Cheburnet fans want one phonebook for all. We read two",
        "Do names resolve to the same places for everyone?",
        "Looking for rewritten entries in the address book",
        "Directory under a magnifying glass",
        "Notes of two witnesses, side by side",
        "Questioning DNS twice, in different rooms",
        "Detective work with IP addresses. Hat and trench coat provided",
        "Sorting honest answers from suspicious ones, gently",
        "Quick audit of the address book",
        "Calling directory assistance in two cities",
        "If an address looks suspiciously handy, we ask again",
        "Ruler held against every answer",
        "Hunting for a name with a different address in transit",
        "Verifying who lives at which address",
        "Cross-checking every address with a trusted friend",
        "Proofreading what DNS said, with a red pen",
        "Asking an honest resolver for its opinion",
        "We whisper a name; two servers shout back addresses",
        "TSPU box swears the address is correct. We still compare",
        "A name, an address and a tiny bit of suspicion",
        "RKN-chan: «That name lives in my registry!» DNS: «It moved»",
        "Peering at the reply for signs of editing",
        "Making sure the name leads where it should",
        "Do the answers match? A game of memory for servers",
        "One name, many answers: sorting out the family reunion",
        "Two phonebooks, read line by line",
        "Fast answer versus honest answer: ding ding, round one",
        "The directory tells its tale twice. Do the tales match?",
        "Checking the postal address, not the postcard",
        "Is the phonebook TSPU-edited? Comparing with an unedited copy",
        "Someone moved the signpost? We brought a compass",
        "DPI doorman and DNS argue about who lives where. We referee",
    ),
    "dns_servers": (
        "Calling DNS servers: «Hello, anyone home?»",
        "Asking each one three times — just in case…",
        "Checking who really picked up the phone…",
        "Phone list the size of a phone book. We call everyone",
        "Honey badger runs down the server list with a stopwatch",
        "TSPU box guards port 53. Ports 853 and 443 wave from afar",
        "RKN-chan crossed some servers off her list. We knock anyway",
        "Knocking on port 53, port 853 and port 443",
        "Three questions to every server, then we compare",
        "«Are you alive? Are you quick?» — the same question to everyone",
        "DNS server beauty contest, speed round",
        "Which servers are home and which are on holiday?",
        "A hit parade of DNS servers",
        "Three tries per server. The third is for luck",
        "Waiting for servers to pick up. Hold music: silence",
        "Sorting the servers by who answers fastest",
        "Doors 53, 853 and 443: plain, private and «looks like the web»",
        "DNS server speed dating: three questions each",
        "Who is awake, who is slow, and who is silent?",
        "RKN-chan's registry lists servers too. We check who still answers",
        "TSPU box and our stopwatch both time DNS answers. Rivals",
        "Fake news: «All DNS servers are fast». Stopwatch ready",
        "Not trusting one answer: asking three times",
        "A race between servers, with a patient referee",
        "Rating the servers on speed and manners",
        "The ISP's DNS gets a call too. Don't tell it we called the others",
        "Interviewing resolvers, three questions each",
        "Taking attendance among the world's DNS servers",
        "Poking the same server a few times to check it's consistent",
        "Do they answer the same way every time? Asking again and again",
        "DPI listens on port 53 like a neighbour with a glass to the wall",
        "Port 53 is gossip, port 853 is a whisper, port 443 is a disguise",
        "Phoning dozens of servers, with sympathy for the switchboard",
        "Looking for the quick ones in a big crowd",
        "Servers get three chances to answer, like in a fairy tale",
        "Timing DNS answers to the millisecond",
        "Going door to door through the DNS neighbourhood",
        "Learning which servers are quick on the draw",
        "Honey badger counts the servers still at home. On fingers",
        "Testing servers' reflexes, three taps each",
        "Writing down who answered and how fast",
        "Stopwatch on every reply",
        "Passing the baton, server to server",
        "Waiting for a reply: the great art of resolver patience",
        "Checking the lights in every server's windows",
        "Asking many friendly servers the same simple thing",
        "Servers who keep their promises get a gold star",
        "Who answers on the plain port and who prefers encryption?",
        "RKN-chan hums at the switchboard. We dial on",
        "Worn-out servers? We just call them again, politely",
        "Quiz show: «Who wants to be a resolver?»",
        "ISP's own DNS gets the same three questions as everyone else",
    ),
    "dns_lookup": (
        "Finding where the site lives. Address, floor, neighbours",
        "Looking up the site's address. They say it's always DNS",
        "Asking the directories: «Where is this one registered?»",
        "Following the site's trail. The trail is fresh",
        "Plotting a route to the site. With layovers",
        "Counting the hops on the way to the site",
        "Pinging the site. «You there?» «…» «How about now?»",
        "Seeing who shares the site's address",
        "IP neighbours are like flatmates: you don't pick them",
        "Was the site caught in a block aimed at its neighbour?",
        "Finding whose address this is. Not 127.0.0.1, we hope",
        "Measuring the road to the site in steps",
        "Asking every router we meet for directions",
        "One does not simply walk to the site. We trace it",
        "Cross-checking the address in several directories",
        "Finding the hop where packets go missing",
        "The honey badger sniffs every hop along the route",
        "A hop stays silent. Proud, or a black box",
        "Guessing where the TSPU box sits. It never signs in",
        "Peeking at the site's registration",
        "Building a file on the site: address, path, neighbours",
        "Site, your address please. Thank you. Checking",
        "We'll go by IP. First, let's learn the IP",
        "Knocking on the site and timing the answer",
        "Route ready? Recalculating, says the navigator",
        "Do different directories give the same address?",
        "Looking for the site on a very large map",
        "Counting how many hands a packet passes through",
        "Address found. Now, how to get there",
        "Checking the road doesn't end at a block page",
        "«Where to?» asks every hop. We answer honestly",
        "A tourist packet rides to the site, snapping photos",
        "Interviewing the site: from where, living where",
        "Did the site move without telling anyone?",
        "Ping replies, so it's alive. Timing it",
        "Calling the site again: it may not have heard",
        "Drawing the path to the site. It's a winding one",
        "Looking for the hop with the barrier down",
        "Asking outside services. For a second opinion",
        "Is the site's neighbour blocked? It happens",
        "Address, path, neighbours — filling in the form",
        "Knock, knock, site. Where do you live?",
        "Checking the site wasn't sent into exile",
        "Counting milliseconds to the site and back",
        "Whose subnet is it? Hopefully not a carpet-blocked one",
        "Finding out who owns the address",
        "Tracing hop by hop, like beads on a string",
        "Site found? Now finding the way to it",
        "The honey badger unfolds a map. Paper, just in case",
        "Gathering everything about the address. Nothing personal",
    ),
}

__all__ = ["EN"]
