"""Страница Hosts: разбор блоков, снимок, черновик и запись одной кнопкой."""

from __future__ import annotations

import os
import unittest
from types import SimpleNamespace
from unittest.mock import patch

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

from PyQt6.QtWidgets import QApplication

from hosts.draft import HostsDraft, build_block_rows
from hosts.hosts_blocks import (
    BLOCK_ADOBE,
    BLOCK_MAX,
    BLOCK_TELEGRAM,
    BLOCK_USER,
    BLOCK_ZAPRETGUI,
    parse_hosts_blocks,
)
from hosts.page_snapshot import (
    CATEGORY_DIRECT,
    CATEGORY_OTHER,
    HostsPageSnapshot,
    HostsServiceEntry,
    build_page_snapshot,
)


BEGIN = "# >>> zapretgui:hosts managed begin >>>"
END = "# <<< zapretgui:hosts managed end <<<"


def _managed(*lines: str) -> str:
    return "\n".join([BEGIN, "# Generated by ZapretGUI. Do not edit this block manually.", *lines, END, ""])


# ── поддельный каталог ─────────────────────────────────────────

# Alpha: адреса p2 = адреса p1 и ещё один (как comss_dns у Truth Social).
# Beta: у p1 и p2 адреса одинаковые.
_ROWS = {
    ("Alpha", "p1"): [("alpha.example", "1.1.1.1")],
    ("Alpha", "p2"): [("alpha.example", "1.1.1.1"), ("alpha.example", "2.2.2.2")],
    ("Beta", "p1"): [("beta.example", "3.3.3.3")],
    ("Beta", "p2"): [("beta.example", "3.3.3.3")],
    ("Direct", "hosts"): [("direct.example", "4.4.4.4"), ("direct.example", "2a00::4")],
}


def _candidates(service: str, profile: str) -> dict[str, list[str]]:
    result: dict[str, list[str]] = {}
    for domain, ip in _ROWS[(service, profile)]:
        result.setdefault(domain, []).append(ip)
    return result


_PROFILE_INDEX = {
    "dns_profiles": ["hosts", "p1", "p2"],
    "dns_profile_names": {"hosts": "Вкл. (активировать hosts)", "p1": "Профиль 1", "p2": "Профиль 2"},
    "services": ["Direct", "Alpha", "Beta"],
    "available_by_service": {"Direct": ["hosts"], "Alpha": ["p1", "p2"], "Beta": ["p1", "p2"]},
    "has_proxy_by_service": {"Direct": False, "Alpha": True, "Beta": True},
    "category_by_service": {"Alpha": "other", "Beta": "other"},
    "icon_by_service": {},
    "service_id_by_name": {},
    "direct_profile": "hosts",
    "domain_names_by_service": {
        "Direct": ["direct.example"],
        "Alpha": ["alpha.example"],
        "Beta": ["beta.example"],
    },
    "profile_domain_ip_candidates_by_service": {
        "Direct": {"hosts": _candidates("Direct", "hosts")},
        "Alpha": {"p1": _candidates("Alpha", "p1"), "p2": _candidates("Alpha", "p2")},
        "Beta": {"p1": _candidates("Beta", "p1"), "p2": _candidates("Beta", "p2")},
    },
}


def _fake_catalog():
    return (
        patch("hosts.proxy_domains.get_services_profile_index", return_value=_PROFILE_INDEX),
        patch("hosts.proxy_domains.get_service_domain_ip_rows", side_effect=lambda s, p: list(_ROWS.get((s, p), []))),
        patch(
            "hosts.proxy_domains.get_dns_profile_display_name",
            side_effect=lambda p: _PROFILE_INDEX["dns_profile_names"].get(p, p),
        ),
    )


def _snapshot(hosts_text: str, *, saved: dict[str, str] | None = None, ipv6: bool = True) -> HostsPageSnapshot:
    first, second, third = _fake_catalog()
    with first, second, third:
        return build_page_snapshot(
            hosts_text=hosts_text,
            hosts_path="hosts",
            hosts_exists=True,
            readable=True,
            read_only=False,
            ipv6_available=ipv6,
            saved_selection=saved,
        )


def _written_block(selection: dict[str, str], *, ipv6: bool = True) -> str:
    rows = build_block_rows(
        selection,
        {key: tuple(value) for key, value in _ROWS.items()},
        ipv6_available=ipv6,
    )
    return _managed(*(f"{ip} {domain}" for domain, ip in rows))


class HostsBlocksParseTests(unittest.TestCase):
    def test_hosts_text_is_split_by_owner(self) -> None:
        text = "\n".join(
            [
                "# comment",
                "10.0.0.1 manual.example",
                BEGIN,
                "2.2.2.2 managed.example",
                END,
                "# --- Telegram Proxy (auto-managed by Zapret 2 GUI) ---",
                "127.0.0.1 web.telegram.org",
                "",
                "# MAX BLOCKED BY ZAPRET GUI",
                "0.0.0.0 max.ru",
                "# END MAX BLOCK",
                "# Adobe Activation Block",
                "# Generated by Zapret-WinGUI",
                "0.0.0.0 lmlicenses.wip4.adobe.com",
                "",
                "10.0.0.2 another.example",
            ]
        )

        blocks = {block.kind: block.lines for block in parse_hosts_blocks(text)}

        self.assertEqual(blocks[BLOCK_ZAPRETGUI], ("2.2.2.2 managed.example",))
        self.assertEqual(blocks[BLOCK_TELEGRAM], ("127.0.0.1 web.telegram.org",))
        self.assertEqual(blocks[BLOCK_MAX], ("0.0.0.0 max.ru",))
        # У блока Adobe нет строки конца: он кончается на первой пустой строке.
        self.assertEqual(blocks[BLOCK_ADOBE], ("0.0.0.0 lmlicenses.wip4.adobe.com",))
        self.assertEqual(blocks[BLOCK_USER], ("10.0.0.1 manual.example", "10.0.0.2 another.example"))

    def test_managed_block_keeps_every_address_of_a_domain(self) -> None:
        snapshot = _snapshot(_written_block({"Alpha": "p2"}))

        block = snapshot.block(BLOCK_ZAPRETGUI)
        self.assertEqual(block.lines, ("1.1.1.1 alpha.example", "2.2.2.2 alpha.example"))


class HostsBlockRowsTests(unittest.TestCase):
    def test_draft_builds_the_same_rows_as_hosts_manager(self) -> None:
        from hosts import hosts as hosts_module

        selection = {"Alpha": "p2", "Beta": "p1", "Direct": "hosts"}
        with patch.object(hosts_module, "get_service_domain_ip_rows", side_effect=lambda s, p: list(_ROWS[(s, p)])):
            manager_rows, _requested = hosts_module._build_service_selection_rows(selection)

        draft_rows = build_block_rows(
            selection,
            {key: tuple(value) for key, value in _ROWS.items()},
            ipv6_available=True,
        )
        self.assertEqual(draft_rows, manager_rows)


class HostsPageSnapshotTests(unittest.TestCase):
    def test_every_written_selection_is_read_back_the_same(self) -> None:
        for selection in (
            {"Alpha": "p1"},
            {"Alpha": "p2"},
            {"Beta": "p1"},
            {"Beta": "p2"},
            {"Direct": "hosts", "Alpha": "p2", "Beta": "p2"},
        ):
            with self.subTest(selection=selection):
                snapshot = _snapshot(_written_block(selection), saved=selection)
                current = {entry.name: entry.current for entry in snapshot.services if entry.current}
                self.assertEqual(current, selection)

    def test_fuller_profile_wins_even_without_saved_selection(self) -> None:
        # Адреса p1 — часть адресов p2: без выбора из настроек всё равно p2.
        snapshot = _snapshot(_written_block({"Alpha": "p2"}))

        self.assertEqual(snapshot.service("Alpha").current, "p2")

    def test_snapshot_reads_hosts_without_writing(self) -> None:
        import tempfile
        from pathlib import Path

        from hosts import hosts as hosts_module
        from hosts import page_snapshot

        with tempfile.TemporaryDirectory() as tmp:
            missing = Path(tmp) / "etc" / "hosts"
            first, second, third = _fake_catalog()
            with (
                first,
                second,
                third,
                patch.object(hosts_module, "HOSTS_PATH", missing),
                patch("hosts.proxy_domains.get_hosts_catalog_signature", return_value=None),
                patch("hosts.proxy_domains.load_user_hosts_selection", return_value={}),
                patch("hosts.ipv6_detection.is_ipv6_available", return_value=True),
                patch.object(page_snapshot, "_SNAPSHOT", None),
                patch.object(hosts_module.HostsManager, "is_hosts_file_accessible") as write_probe,
            ):
                hosts_module.invalidate_hosts_file_cache()
                snapshot = page_snapshot.load_page_snapshot()

            write_probe.assert_not_called()
            self.assertFalse(snapshot.hosts_exists)
            self.assertTrue(snapshot.readable)
            self.assertFalse(missing.parent.exists())
        hosts_module.invalidate_hosts_file_cache()


def _manual_snapshot(block_lines: tuple[str, ...] = (), user_lines: tuple[str, ...] = (), **kwargs) -> HostsPageSnapshot:
    text_lines: list[str] = list(user_lines)
    if block_lines:
        text_lines = [BEGIN, *block_lines, END, *user_lines]
    return HostsPageSnapshot(
        services=(
            HostsServiceEntry("Direct", CATEGORY_DIRECT, "fa5s.globe", None, ("hosts",), kwargs.pop("direct", None)),
            HostsServiceEntry("Alpha", CATEGORY_OTHER, "fa5s.globe", None, ("p1", "p2"), kwargs.pop("alpha", None)),
            HostsServiceEntry("Beta", CATEGORY_OTHER, "fa5s.globe", None, ("p1",), kwargs.pop("beta", None)),
        ),
        dns_profiles=(("p1", "Профиль 1"), ("p2", "Профиль 2")),
        direct_profile="hosts",
        rows={key: tuple(value) for key, value in _ROWS.items()},
        blocks=tuple(parse_hosts_blocks("\n".join(text_lines))),
        **kwargs,
    )


class HostsDraftTests(unittest.TestCase):
    def test_clicks_change_only_the_draft_until_values_match_again(self) -> None:
        draft = HostsDraft(_manual_snapshot())

        self.assertFalse(draft.is_dirty())
        self.assertTrue(draft.set("Alpha", "p1"))
        self.assertTrue(draft.is_dirty())
        self.assertEqual(draft.changed_services(), ["Alpha"])
        self.assertEqual(draft.preview().added, ("1.1.1.1 alpha.example",))

        self.assertTrue(draft.set("Alpha", None))
        self.assertFalse(draft.is_dirty())

    def test_unknown_profile_is_refused(self) -> None:
        draft = HostsDraft(_manual_snapshot())

        self.assertFalse(draft.set("Beta", "p2"))
        self.assertFalse(draft.is_dirty())

    def test_dns_for_all_skips_services_without_that_profile(self) -> None:
        draft = HostsDraft(_manual_snapshot())

        changed, skipped = draft.set_all_dns("p2")

        self.assertEqual((changed, skipped), (1, ["Beta"]))
        self.assertEqual(draft.value("Direct"), None)
        self.assertEqual(draft.selection(), {"Alpha": "p2"})

    def test_preview_lists_removed_lines_and_user_lines_with_same_domain(self) -> None:
        snapshot = _manual_snapshot(
            block_lines=("3.3.3.3 beta.example",),
            user_lines=("9.9.9.9 alpha.example",),
            beta="p1",
        )
        draft = HostsDraft(snapshot)
        draft.set("Beta", None)
        draft.set("Alpha", "p1")

        preview = draft.preview()

        self.assertEqual(preview.added, ("1.1.1.1 alpha.example",))
        self.assertEqual(preview.removed, ("3.3.3.3 beta.example",))
        self.assertEqual(preview.shadowed, ("9.9.9.9 alpha.example",))

    def test_rebase_keeps_only_changes_not_yet_written(self) -> None:
        draft = HostsDraft(_manual_snapshot())
        draft.set("Alpha", "p1")
        draft.set("Beta", "p1")

        draft.rebase(_manual_snapshot(block_lines=("1.1.1.1 alpha.example",), alpha="p1"))

        self.assertEqual(draft.changed_services(), ["Beta"])

    def test_adobe_toggle_is_part_of_the_draft(self) -> None:
        draft = HostsDraft(_manual_snapshot())

        self.assertTrue(draft.set_adobe(True))
        self.assertTrue(draft.adobe_changed)
        self.assertTrue(draft.set_adobe(False))
        self.assertFalse(draft.is_dirty())

    def test_lines_of_no_selected_service_make_the_draft_dirty(self) -> None:
        # Строка сервиса, которого нет в каталоге, и выбранный Beta.
        snapshot = _manual_snapshot(
            block_lines=("3.3.3.3 beta.example", "5.5.5.5 gone.example"),
            beta="p1",
        )
        draft = HostsDraft(snapshot)

        self.assertEqual(draft.stale_lines, ("5.5.5.5 gone.example",))
        self.assertTrue(draft.is_dirty())
        self.assertFalse(draft.has_user_changes())
        self.assertEqual(draft.preview().removed, ("5.5.5.5 gone.example",))

        draft.reset()
        self.assertTrue(draft.is_dirty(), "лишние строки остаются до записи")

    def test_ipv6_lines_are_not_stale_while_ipv6_is_down(self) -> None:
        snapshot = _manual_snapshot(
            block_lines=("4.4.4.4 direct.example", "2a00::4 direct.example"),
            direct="hosts",
            ipv6_available=False,
        )

        self.assertEqual(HostsDraft(snapshot).stale_lines, ())


class HostsPageTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls._app = QApplication.instance() or QApplication([])

    def _page(self, snapshot: HostsPageSnapshot):
        from hosts.ui.page import HostsPage

        feature = SimpleNamespace(
            peek_page_snapshot=lambda: snapshot,
            create_snapshot_worker=lambda request_id, parent=None: None,
        )
        page = HostsPage(deps=SimpleNamespace(hosts_feature=feature))
        self.addCleanup(page.deleteLater)
        page._set_snapshot(snapshot)
        page.resize(900, 700)
        page.show()
        QApplication.processEvents()
        return page

    def test_toggle_shows_draft_bar_and_cancel_hides_it(self) -> None:
        page = self._page(_manual_snapshot())

        self.assertFalse(page.draft_bar.isVisible())
        page._on_service_activated("Direct", page.mapToGlobal(page.rect().center()))

        self.assertTrue(page.draft_bar.isVisible())
        self.assertTrue(page.draft_bar.cancel_button.isEnabled())
        page._reset_draft()
        self.assertFalse(page.draft_bar.isVisible())

    def test_extra_lines_offer_apply_without_cancel(self) -> None:
        page = self._page(_manual_snapshot(block_lines=("5.5.5.5 gone.example",)))

        self.assertTrue(page.draft_bar.isVisible())
        self.assertFalse(page.draft_bar.cancel_button.isEnabled())
        self.assertIn("1", page.draft_bar.summary_label.text())

    def test_snapshot_read_before_apply_does_not_replace_fresh_result(self) -> None:
        page = self._page(_manual_snapshot())
        fresh = page._snapshot
        page._snapshot_epoch = page._write_epoch
        page._write_epoch += 1  # «Применить» записал файл, пока шло чтение.

        with patch.object(page._snapshot_runtime, "is_current", return_value=True):
            page._on_snapshot_loaded(1, _manual_snapshot(block_lines=("3.3.3.3 beta.example",), beta="p1"))

        self.assertIs(page._snapshot, fresh)
        self.assertTrue(page._snapshot_pending)

    def test_filter_bar_is_named_for_screen_reader(self) -> None:
        from ui import segmented_accessibility

        page = self._page(_manual_snapshot())

        self.assertEqual(getattr(page.filter_bar, segmented_accessibility._TITLE_ATTR), "Какие сервисы показать")

    def test_page_receives_narrow_feature_not_services(self) -> None:
        import dataclasses

        from app.feature_facades.hosts import HostsFeature

        names = {field.name for field in dataclasses.fields(HostsFeature)}
        self.assertTrue({"peek_page_snapshot", "create_snapshot_worker", "create_apply_worker"} <= names)
        self.assertFalse(any("manager" in name or "runtime" in name for name in names))


if __name__ == "__main__":
    unittest.main()
