"""Весёлые фразы окна обновления: пока качается — не скучно.

Правило то же, что у BlockCheck (``blockcheck/ui/fun_texts.py``): шутка
сопровождает работу, но не заменяет смысл. Проценты, скорость и ошибки
пишутся рядом точно и серьёзно, здесь — только настроение.

Наборы нарочно большие: фразы идут в случайном порядке без повторов
(см. ``ui.widgets.fun.ticker``), и от обновления к обновлению текст разный.
Каждая фраза — одна короткая строка: окно-продолжение не переносит текст.
"""

from __future__ import annotations

_RU: dict[str, tuple[str, ...]] = {
    "preparing": (
        "Будим сервер обновлений: «Эй, у тебя тут новая версия завалялась?»",
        "Ищем, с какой полки взять свежую версию…",
        "Разминаемся перед забегом…",
        "Проверяем шнурки. Сейчас побежим",
        "Медоед надевает кроссовки…",
        "Стучимся на сервер. Вежливо, три раза",
        "Медоед потягивается и открывает один глаз…",
        "Выбираем самую короткую дорогу до сервера",
        "Сверяем карту: где тут свежая версия?",
        "Достаём из шкафа большую сумку для байтов",
        "Заводим мотор. Он немного кашляет, но заводится",
        "Медоед пьёт кофе перед дорогой",
        "Договариваемся с сервером о встрече",
        "Расчищаем место под новую версию",
        "Проверяем, на месте ли интернет. На месте!",
        "Ставим чайник: загрузка будет быстрее, чем он закипит",
        "Медоед изучает маршрут по бумажной карте",
        "Ждём, пока сервер найдёт нужный файл…",
        "Считаем до трёх. Раз… два…",
        "Подтягиваем рукава, сейчас начнём",
    ),
    "downloading": (
        "Выгружаем свежие байты прямо из печи…",
        "Медоед несёт обновление в зубах. Аккуратно, не уронить!",
        "Байты бегут строем, раз-два, раз-два…",
        "Качаем новую версию. Старая делает вид, что не ревнует",
        "Несём новые возможности. Ошибки оставили дома",
        "Складываем байтики в коробочку по одному…",
        "Скорость хорошая, провайдер пока не заметил",
        "Каждый байт проверен лично медоедом",
        "Почти как пицца: горячее, свежее, скоро будет у вас",
        "DPI провожает обновление грустным взглядом",
        "Если прислушаться, слышно, как шуршат пакеты",
        "Тянем-потянем — вытянули ещё мегабайт",
        "Медоед бежит по проводам с рюкзаком байтов",
        "Байты едут в вагоне первого класса",
        "Мегабайты выстроились в очередь. Не толкаемся!",
        "Новая версия уже в пути и машет вам рукой",
        "Укладываем байты плотнее, чтобы влезло больше",
        "Пакеты бегут через полмира, чтобы попасть к вам",
        "Медоед несёт обновление и насвистывает песенку",
        "Байт за байтом — так и строятся программы",
        "Ловим байты сачком, пока они пролетают мимо",
        "Байты прибывают точно по расписанию",
        "Если загрузка застрянет, медоед подтолкнёт",
        "Медоед пересчитывает байты: сходится!",
        "Курьер уже в вашем подъезде, поднимается на лифте",
        "Байты не пахнут, но эти особенно свежие",
        "Пакеты проходят таможню без досмотра",
        "Где-то в серверной радостно мигают лампочки",
        "Медоед обогнал черепаху. Черепаха не обиделась",
        "Наполняем ведро байтами. Уже больше половины… почти",
        "Каждый мегабайт — маленькая победа",
        "Новая версия едет к вам на самокате",
        "Байты бегут эстафетой и передают друг другу палочку",
        "Мимо пролетел мегабайт. А вот и ещё один",
        "Медоед заметил: сегодня байты особенно послушные",
        "Шуршим пакетами, но не теми, что из магазина",
        "Почтовый голубь отдыхает: у нас всё быстрее",
        "Скачиваем новую версию без смс и регистрации",
        "Байты пристёгнуты, полёт проходит нормально",
        "Ещё немного — и новая версия будет дома",
    ),
    "installing": (
        "Сверяем контрольную сумму: всё своё, ничего чужого",
        "Передаём эстафету установщику…",
        "Программа сейчас закроется — это не поломка, это переезд",
        "Собираем чемоданы. До встречи в новой версии!",
        "Проверяем, что ни один байт не потерялся в дороге",
        "Медоед раскладывает файлы по местам",
        "Снимаем старые обои, клеим новые",
        "Установщик засучил рукава",
        "Выключаем свет в старой версии",
        "Медоед проверяет, всё ли упаковано",
        "Наклеиваем на коробки надписи «Хрупкое»",
        "Грузчики уже в пути, не переживайте",
        "Старая версия собирает вещи и пишет записку новой",
        "Сейчас будет секунда тишины — так и задумано",
        "Распаковываем новую версию, осторожно, не порежьтесь",
        "Медоед закручивает последние винтики",
        "Сдаём ключи от старой квартиры",
        "Прощаемся со старой версией. Она была хорошей",
    ),
    "failed": (
        "Медоед споткнулся. Бывает с лучшими из нас",
        "Байты разбежались. Попробуем собрать ещё раз?",
        "Сервер отвернулся. Может, он просто занят?",
        "Медоед отряхнулся и готов бежать снова",
        "Дорогу перекрыли. Поищем объезд?",
        "Не вышло с первого раза — выйдет со второго",
        "Где-то по пути пакеты свернули не туда",
        "Медоед почесал затылок и задумался",
        "Курьер заблудился. Отправим ещё одного?",
        "Связь споткнулась. Ничего страшного, бывает",
    ),
    "restarting": (
        "Старая версия передаёт дела новой…",
        "Медоед переезжает в новый дом",
        "Меняем колёса прямо на ходу",
        "Новая версия уже надевает кроссовки",
        "Раскладываем свежие файлы по полочкам",
        "Пять секунд — полёт нормальный",
        "Старая версия машет платочком",
        "Проверяем, что ничего не забыли в старой квартире",
        "Медоед вешает новые шторы",
        "Расставляем мебель в новой версии",
        "Новая версия моет руки перед работой",
        "Включаем свет в новых комнатах",
        "Медоед проверяет, закрыт ли кран",
        "Новая версия разминается перед выходом",
        "Ещё чуть-чуть — и всё заработает как новое",
        "Медоед застилает кровать в новом доме",
        "Старая версия оставила новой записку с советами",
        "Протираем пыль с новых файлов",
        "Новая версия знакомится с соседями",
        "Медоед проверяет, все ли файлы на месте",
        "Перевешиваем табличку на двери",
        "Новая версия поправляет галстук",
        "Медоед вкручивает лампочку в прихожей",
        "Почти готово, осталось найти пульт",
        "Новоселье! Торт будет чуть позже",
        "Новая версия зевает и просыпается",
        "Медоед открывает окна, проветриваем",
        "Расставляем ярлыки по местам",
        "Новая версия ищет тапочки",
        "Медоед кладёт коврик у двери",
        "Ещё секунда — и откроется новая версия",
        "Поливаем цветы в новом доме",
        "Новая версия запоминает, где что лежит",
        "Медоед вешает на стену любимую картину",
    ),
    "whats_new": (
        "Листаем свежий список изменений…",
        "Достаём заметки к выпуску…",
        "Медоед читает список изменений вслух…",
        "Разворачиваем свиток с новостями…",
        "Ищем, что изменилось с прошлого раза…",
        "Сдуваем пыль со списка изменений…",
        "Медоед надевает очки для чтения…",
        "Собираем все новости в одну стопку…",
        "Записываем, что нового, крупным шрифтом…",
        "Медоед раскладывает новости по полочкам…",
    ),
}

_EN: dict[str, tuple[str, ...]] = {
    "preparing": (
        "Waking up the update server: «Got a new version lying around?»",
        "Stretching before the run…",
        "The honey badger is lacing up its sneakers…",
        "Knocking on the server's door. Politely, three times",
        "The honey badger opens one eye…",
        "Picking the shortest road to the server",
        "Grabbing a big bag for the bytes",
        "Starting the engine. It coughs, but it starts",
        "The honey badger has a coffee before the trip",
        "Making room for the new version",
        "Checking the internet is still there. It is!",
        "Counting to three. One… two…",
    ),
    "downloading": (
        "Unloading fresh bytes straight from the oven…",
        "The honey badger carries the update in its teeth. Careful!",
        "Bytes are marching in line, left-right, left-right…",
        "Bringing new features. Bugs stayed at home",
        "Every byte personally checked by the honey badger",
        "DPI watches the update leave with a sad look",
        "Packing the bytes into a little box one by one…",
        "Pulling and pulling — out came another megabyte",
        "The honey badger runs along the wires with a backpack",
        "The bytes are travelling first class",
        "Megabytes are queuing up. No pushing!",
        "The new version is on its way and waving at you",
        "Packets cross half the world to reach you",
        "Catching bytes with a net as they fly by",
        "The honey badger counted the bytes: all there!",
        "The courier is already in your elevator",
        "Somewhere in a server room, lights blink happily",
        "Every megabyte is a small victory",
        "The new version rides to you on a scooter",
        "Bytes are buckled up, the flight is smooth",
        "Almost there — the new version is nearly home",
    ),
    "installing": (
        "Checking the checksum: everything is ours",
        "Passing the baton to the installer…",
        "The app is about to close — it is moving, not crashing",
        "Packing the suitcases. See you in the new version!",
        "Making sure no byte got lost on the way",
        "The honey badger puts the files in their places",
        "The installer rolls up its sleeves",
        "Turning off the lights in the old version",
        "Labelling the boxes «Fragile»",
        "A second of silence is coming — that is on purpose",
        "Handing over the keys to the old apartment",
    ),
    "failed": (
        "The honey badger tripped. Happens to the best of us",
        "Bytes ran away. Shall we try again?",
        "The server turned away. Maybe it is just busy?",
        "The honey badger dusted itself off and is ready to run again",
        "The road is closed. Shall we take a detour?",
        "Packets took a wrong turn somewhere",
        "The courier got lost. Send another one?",
    ),
    "restarting": (
        "The old version hands over to the new one…",
        "The honey badger is moving into a new home",
        "Changing the wheels on the go",
        "The new version is lacing up its sneakers",
        "Putting fresh files on the shelves",
        "The old version waves a handkerchief",
        "Checking nothing was left in the old apartment",
        "The honey badger hangs new curtains",
        "Turning on the lights in the new rooms",
        "The new version washes its hands before work",
        "The old version left a note with tips for the new one",
        "Dusting off the new files",
        "The new version straightens its tie",
        "Housewarming! The cake comes a bit later",
        "The new version yawns and wakes up",
        "The honey badger opens the windows for fresh air",
        "The new version is looking for its slippers",
        "One more second — and the new version opens",
    ),
    "whats_new": (
        "Flipping through the fresh changelog…",
        "Getting the release notes…",
        "The honey badger reads the changelog out loud…",
        "Unrolling the scroll of news…",
        "The honey badger puts on its reading glasses…",
        "Looking for what changed since last time…",
    ),
}


def phrases(kind: str, language: str | None = None) -> tuple[str, ...]:
    table = _EN if str(language or "").lower().startswith("en") else _RU
    return table.get(kind) or _RU.get(kind) or _RU["downloading"]


__all__ = ["phrases"]
