"""Английские весёлые фразы окна обновления (см. ``fun_texts.py``)."""

from __future__ import annotations

EN: dict[str, tuple[str, ...]] = {
    "preparing": (
        "Waking up the update server: «Got a new version lying around?»",
        "Stretching before the run…",
        "The honey badger is lacing up its sneakers…",
        "Knocking on the server's door. Politely, three times",
        "The honey badger opens one eye…",
        "Picking the shortest road to the server",
        "Grabbing a big bag for the bytes",
        "Starting the engine. It coughs, but it starts",
        "The honey badger has a coffee before the trip",
        "Making room for the new version",
        "Checking the internet is still there. It is!",
        "Counting to three. One… two…",
        "RKN-chan is dozing at her desk. Tiptoeing to the server",
        "Asking the TSPU box for directions. It just hums nervously",
        "Quietly, quietly… RKN-chan has her stamp ready",
        "Our tiny nervous byte is double-checking its shoelaces",
        "Sneaking up on the server like a ninja in slippers",
        "Is this the update server? «No, it's a toaster.» Oh, sorry",
        "Hello, server? We come in peace and with a very big bucket",
        "Our ISP says the line is great. Our ISP says many things",
        "Warming up the bytes. Cold ones catch colds",
        "Honey badger does not care about queues. Excusing itself now",
        "A tiny byte asks: «Are we there yet?» We have not even left",
        "Printing the permission slip. RKN-chan wants it in triplicate",
        "Studying the route. All roads lead to «Blocked»? Not ours",
        "Hiding the update under a hat. It's a disguise, you see",
        "Putting on a trench coat and sunglasses. Very inconspicuous",
        "Politely ignoring the sign that says «Nothing to see here»",
        "Offering the TSPU box a cookie. It overheats from joy",
        "«Is that the cloud?» «Yes, we are drizzling bytes today»",
        "Our ISP promises full speed ahead. Fingers crossed anyway",
        "Flipping through RKN-chan's registry. Hoping we are not in it",
        "Booking a table at the server. Table for one very large file",
        "Rehearsing small talk with the server about the weather",
        "Tying a string to the byte so it does not wander off",
        "Whispering to the router: «Be strong, it's a long one»",
        "Doing breathing exercises with the TSPU box. In, out, no throttling",
        "Preparing excuses for RKN-chan. First one: «It's a cat video»",
        "Dusting off the «I was just updating» speech",
        "Unfolding the map. A big red «BLOCKED» stamp covers half of it",
        "Honey badger put its tie on as a belt. Meeting the server anyway",
        "Breaking news: update leaves the house, nobody notices",
        "Fanning the TSPU box with a newspaper. It is running warm again",
        "Saying a quiet prayer to the god of Wi-Fi bars",
        "Is it a bird? Is it a plane? No, just a very hopeful packet",
        "Sending the server a postcard: «Weather great, wish you were fast»",
        "A tiny nervous byte hides behind the bigger bytes. Typical",
        "Squeezing past the ISP's elbows. Excuse us, excuse us",
        "Putting on a brave face. And a spare brave face for later",
        "Reminding the server we have an appointment. It forgot, naturally",
        "Taking a number at the server's counter. We are number one!",
        "Wearing socks so the cables do not hear our steps",
    ),
    "downloading": (
        "Unloading fresh bytes straight from the oven…",
        "The honey badger carries the update in its teeth. Careful!",
        "Bytes are marching in line, left-right, left-right…",
        "Bringing new features. Bugs stayed at home",
        "Every byte personally checked by the honey badger",
        "DPI watches the update leave with a sad look",
        "Packing the bytes into a little box one by one…",
        "Pulling and pulling — out came another megabyte",
        "The honey badger runs along the wires with a backpack",
        "The bytes are travelling first class",
        "Megabytes are queuing up. No pushing!",
        "The new version is on its way and waving at you",
        "Packets cross half the world to reach you",
        "Catching bytes with a net as they fly by",
        "The honey badger counted the bytes: all there!",
        "The courier is already in your elevator",
        "Somewhere in a server room, lights blink happily",
        "Every megabyte is a small victory",
        "The new version rides to you on a scooter",
        "Bytes are buckled up, the flight is smooth",
        "Almost there — the new version is nearly home",
        "Downloading quietly. RKN-chan is asleep, do not wake her",
        "TSPU box: «It's not a block, it's a slowdown». Sure, buddy",
        "A tiny nervous byte just crossed the filter. Standing ovation",
        "Honey badger chews through the throttle like it was spaghetti",
        "RKN-chan stamps «BLOCKED» on the wrong envelope. Again",
        "Dear ISP, this is a software update. Yours, a tiny byte",
        "Breaking news: local byte arrives safely, ISP shocked",
        "Paper planes are fashionable again. Bytes fly in formation",
        "Nobody expects a paper plane squadron. RKN-chan certainly did not",
        "Mmm, fresh bytes. Tastes like the future with a hint of cache",
        "Whole IP ranges blocked? Our bytes took the stairs",
        "A byte tripped over the cable and pretended it was a dance move",
        "ISP sneeze detected. Bytes say «bless you» and keep going",
        "Sorry for the wait. The bytes stopped to ask for directions",
        "Honey badger does not care about throttling. It just downloads",
        "RKN-chan checks the registry, finds a cat video, gets distracted",
        "Mid-download tea break! Just kidding, the bytes never rest",
        "Bytes at the border: «Anything to declare?» «Only fresh features»",
        "Hang on, a byte is reading the terms and conditions. All of them",
        "Pssst, TSPU box. Look at that cloud over there. Thanks, bye",
        "A worn-out server wheezes and still hands over a byte. Hero",
        "Do not look at the progress bar. It gets shy and slows down",
        "Waiting in line behind a very large cat video. Rude",
        "Press release from the ISP: «Everything is fine». Everything is fine",
        "Tiny byte: «Are we there yet?» Bigger byte: «Almost»",
        "Passport control for bytes: «Purpose of visit?» «Updating»",
        "Hush, the honey badger is negotiating with a filter box",
        "Prize for the bravest byte: a tiny cookie. Crumbs only",
        "Stage whisper: «Is RKN-chan looking?» «No, she is on her phone»",
        "Pushing bytes through the pipe. Please do not blow into it",
        "Download speed is a state of mind. Ours is optimistic",
        "Fanning the TSPU box with a magazine. It got too excited",
    ),
    "installing": (
        "Checking the checksum: everything is ours",
        "Passing the baton to the installer…",
        "The app is about to close — it is moving, not crashing",
        "Packing the suitcases. See you in the new version!",
        "Making sure no byte got lost on the way",
        "The honey badger puts the files in their places",
        "The installer rolls up its sleeves",
        "Turning off the lights in the old version",
        "Labelling the boxes «Fragile»",
        "A second of silence is coming — that is on purpose",
        "Handing over the keys to the old apartment",
        "Old version: «Do you have to go?» Installer: «Yes. Sorry»",
        "Please do not disturb: the installer is hugging the files",
        "RKN-chan is told it is just a boring installer. She yawns",
        "Dear TSPU box, this is a boring installer. Go back to sleep",
        "Moving boxes: one for the files, one for the cat, one for luck",
        "A tiny nervous byte sits on a box and refuses to be moved",
        "Hammering in the last nail. Ouch. Not the thumb, phew",
        "Honey badger unpacks the boxes. The boxes lose",
        "Assembling the new version without reading the manual. Bold",
        "Spare screws left over? We call those «bonus features»",
        "Clicking «Next» on your behalf. It is a very polite click",
        "Your computer is thinking. Very hard. Maybe about lunch",
        "Overheard in the installer: «Where does this one go?» «Anywhere»",
        "Breaking news: files moved in, neighbours barely noticed",
        "Ssh, the files are sleeping on the new sofa. Almost there",
        "Wiping our feet on the welcome mat. Twice, for luck",
        "Reading the licence agreement at lightning speed. Agreed!",
        "Honey badger supervises the installer. Installer is nervous",
        "Installing like a thief in the night, but a legal one",
        "RKN-chan wants to know what is in the box. Files. Boring",
        "Waving at the ISP. It waves back, very slowly",
        "TSPU box peeks at the installer and goes back to sleep",
        "Found a tiny nervous byte under the sofa. It is joining us",
        "Hanging pictures slightly crooked. That is the charm",
        "Ordering a pizza for the installer. It will not eat. Too busy",
        "Dropping a file. Picking it up. Pretending it was planned",
        "Whistling nonchalantly while the files file in",
        "Is it done yet? Not yet. Is it done yet? Ask the cat",
        "Quick, hide the old version's slippers before it notices",
        "Painting a new sign: «Now with even more new»",
        "Tiny movers carry files one by one. They demanded a snack",
        "Letting the files settle. They are a bit moody after the move",
        "Whoa, careful with that file, it contains fragile jokes",
        "Asking the installer for a break. It said «Never»",
        "Gluing the pieces with hope and a bit of digital tape",
        "Winding the clock. It ticks louder in the new house",
        "Shhh! The installer is counting. It lost count twice already",
        "Honey badger signs the installer's papers with its claw",
        "Smoothing the carpet over the lump. What lump? No lump",
        "Stirring the files gently. Do not shake, do not worry",
        "Our fingers are crossed. That is not part of the installer, though",
    ),
    "failed": (
        "The honey badger tripped. Happens to the best of us",
        "Bytes ran away. Shall we try again?",
        "The server turned away. Maybe it is just busy?",
        "The honey badger dusted itself off and is ready to run again",
        "The road is closed. Shall we take a detour?",
        "Packets took a wrong turn somewhere",
        "The courier got lost. Send another one?",
        "Oops. Our tiny nervous byte fainted. It happens, let us retry",
        "No panic. Panic is also not on the schedule today",
        "Let us pretend this never happened and press retry with style",
        "Take a sip of tea. The update will wait. It is very patient",
        "Honey badger shrugs, cracks its knuckles and says: again",
        "Sad trombone. Now the happy one, on the second attempt",
        "Try again? Honey badger votes yes, and it has claws",
        "Nothing to see here. Retry is still on the menu",
        "RKN-chan cannot block our optimism. Retry!",
        "We would call it a plot twist. The second try is the sequel",
        "Update stumbled and is now pretending to tie its shoe",
        "Even a cat falls off the shelf sometimes, and lands on its feet",
        "Update says: «Give me a minute.» Let us give it a minute",
        "A moment of silence for the lost bytes. Okay, enough. Retry!",
        "Cheer up! Even legends have a blooper reel",
        "Alas! But also: yay, a second chance",
        "Do not worry, we have cookies and also a retry button",
        "Not our finest minute. We have plenty of minutes left",
        "Fake headline: update takes a day off, returns soon",
        "Plan B is just plan A with a bit more confidence",
        "Mistakes were made. Nobody knows by whom. Let us go again",
        "Hugging the progress bar. It is okay, little one",
        "Wait. Do not throw the computer. Throw a smile and press retry",
        "Mission not yet accomplished. Mission still very much on",
        "Hey, at least we tried something exciting",
        "Hold tight. Retrying is a very respectable hobby",
        "Go on, press that button again. It is secretly looking forward",
        "Close, but no cigar. Cigars are bad for you anyway",
        "Apparently the universe wanted a second take",
        "In today's episode, the update loses. In the next, it wins",
        "Rumours of our failure are slightly exaggerated",
        "Take a deep breath and wiggle your toes. Now retry",
        "Our eyes met the error. Nobody blinked. Retry?",
        "Zero stress, one dramatic sigh. Now try again",
        "A gentle pat on the shoulder of the update. It needed it",
        "Maybe the update is just shy and wants a second invitation",
        "Would not be a proper adventure without a small oops",
        "Honey badger remains unbothered. Try to be as unbothered",
        "No hard feelings, update. Come back when you are ready",
        "Please hold the line. Honey badger is warming up round two",
        "Failure is just success taking a coffee break",
        "Silly update, tripping over a flat floor. Try again",
        "All is calm. Sit tight, rub your hands, we go again",
        "Our first answer was a no. We will ask again, with sparkles",
        "Oof. Do you hear that? It is the sound of a retry coming",
        "RKN-chan wishes you luck on the next attempt, grudgingly",
    ),
    "restarting": (
        "The old version hands over to the new one…",
        "The honey badger is moving into a new home",
        "Changing the wheels on the go",
        "The new version is lacing up its sneakers",
        "Putting fresh files on the shelves",
        "The old version waves a handkerchief",
        "Checking nothing was left in the old apartment",
        "The honey badger hangs new curtains",
        "Turning on the lights in the new rooms",
        "The new version washes its hands before work",
        "The old version left a note with tips for the new one",
        "Dusting off the new files",
        "The new version straightens its tie",
        "Housewarming! The cake comes a bit later",
        "The new version yawns and wakes up",
        "The honey badger opens the windows for fresh air",
        "The new version is looking for its slippers",
        "One more second — and the new version opens",
        "RKN-chan wants a word with the new version. It has no time",
        "Out with the old, in with the new, and a mop for the mess",
        "Our tiny nervous byte volunteers to turn off the old lights",
        "TSPU box: «Who goes there?» New version: «A very boring app»",
        "Honey badger pushes the big red restart button. Gently",
        "Brb! Be right back, new and shinier",
        "Closing the app and opening it again. Yes, the classic trick",
        "Old version says goodbye and takes its mug with it",
        "Have you tried turning it off and on again? We just did",
        "Please stay seated while the app is parked in the new garage",
        "Fake headline: app reborn, old version retires to a beach",
        "Hold on, this version feels newer. Let us double-check",
        "RKN-chan is told: nothing happened here. She does not buy it",
        "Bye, old version! Do take your bugs with you",
        "Swapping the engine, the wheels, and the driver's snacks",
        "Be right back with fresh coffee and a fresh version",
        "Reopening the doors. Mind the wet paint, it is still new",
        "A tiny nervous byte presses the start button with both hands",
        "Nothing to see here, please move along, new version loading",
        "Honey badger blows a whistle. The new version marches in",
        "ISP, please be gentle. The new version is a bit shy",
        "Take a deep breath. The app is almost back from vacation",
        "Dimming the old logo. Lighting up the new one",
        "Pssst, TSPU box! New version coming through, look away",
        "Newly renovated version, now with fresh paint smell",
        "Warm applause for the old version. It did its best",
        "We pinch the old version's cheek and wave it goodbye",
        "Zip, zap, restart! A tiny spell for a new beginning",
        "Freshly baked version, still too hot to touch",
        "Honey badger tucks the old version into bed. Very kindly",
        "Restarting the app, not the whole world. No need to panic",
        "Picking a good seat for the new version in the front row",
        "RKN-chan sulks in the corner. The new version just waves",
    ),
    "whats_new": (
        "Flipping through the fresh changelog…",
        "Getting the release notes…",
        "The honey badger reads the changelog out loud…",
        "Unrolling the scroll of news…",
        "The honey badger puts on its reading glasses…",
        "Looking for what changed since last time…",
        "Here is what is new. RKN-chan did not approve any of it",
        "Fresh from the oven, with extra sprinkles of improvement",
        "Presenting the list of new things. Drumroll optional",
        "News! Not the kind RKN-chan stamps «BLOCKED», the good kind",
        "Honey badger highlights the juicy parts. Do read them",
        "Spoiler alert: the new version is a little better than the old",
        "Gossip from the new version: it learned a few new tricks",
        "Hot off the press, and it does not even burn your fingers",
        "Tiny nervous byte presents the changes. Please be kind",
        "Warning: contents may include improvements and joy",
        "Fake headline: app grows up, gets new shoes",
        "Look what the new version brought! No, you cannot return it",
        "Handing over the changelog. Much nicer than RKN-chan's registry",
        "TSPU box cannot throttle good news. Not on our watch",
        "Come closer, the changelog does not bite. The honey badger might",
        "Here is a list of things that got better. Applause, please",
        "Tada! And now, the fine print in a very friendly font",
        "What is new? Glad you asked. It is right below",
        "Ahem. Ladies and gentlemen, the changelog",
        "A very short story: the app got better. Details below",
        "New things ahead. Please hold your excitement in both hands",
        "Fun fact: every line below was typed with love and coffee",
        "Reading it out loud in a dramatic voice. You are welcome",
        "Plot twist: the update actually did something nice",
        "Your app went to the gym. Behold the results",
        "Like a layered cake, but each layer is an improvement",
        "Brought to you by caffeine, patience, and a tiny nervous byte",
        "Before you ask: yes, it is better. The list proves it",
        "RKN-chan peeked at the list and went pale. Mighty good sign",
        "Look, a list! We love lists. Do you love lists?",
        "Notes from the developers, typed with a caffeinated smile",
        "This is the part where we show off a little. Bear with us",
        "Scroll down to see what we have been cooking all this time",
        "Everything in this list is brand new, unlike this joke",
        "Surprise! The app grew a little. Measure it, if you must",
        "Once upon a time there was a bug. Read how it ended",
        "Honey badger approves each line with a nod. And a growl",
        "Items on this list are freshly made and fully proud",
        "Careful, the list is hot. Let it cool for one scroll",
        "Out with the old bugs, in with the shiny stuff",
        "Updates are like socks. Everyone wants the fresh ones",
        "Pssst, over here: the changelog. Do not tell RKN-chan",
        "If this list were a cake, it would be a pretty big one",
        "A drumroll for each line, imaginary but very enthusiastic",
        "Skim it, savour it, or print it and frame it. Your call",
    ),
}

__all__ = ["EN"]
