"""Английские весёлые фразы общих мест программы (см. ``fun_phrases.py``)."""

from __future__ import annotations

EN: dict[str, tuple[str, ...]] = {
    "engine_start": (
        "Starting Zapret. The honey badger puts on a helmet",
        "Starting the bypass. TSPU box, prepare to be surprised",
        "Cranking the engine. It coughed, then caught",
        "Starting. Packets, to your places!",
        "Launch in three, two, one… go!",
        "Starting Zapret. Lucky tambourine within reach",
        "Bypass on. Internet, shoulders back",
        "Starting. RKN-chan, don't turn around",
        "Starts on the first try. Almost",
        "Starting the engine. Stormtrooper RX-78, at ease",
        "Okay, let's go: starting",
        "Starting Zapret. No offence, black boxes",
        "Switching on. The peephole becomes a window",
        "Starting. The honey badger is in the blocks",
        "Off we go! Starting the bypass",
        "Starting the engine. Magic numbers loaded",
        "Go! Packets are putting on disguises",
        "Starting Zapret. Good morning, DPI doorman",
        "Switching on. It won't switch itself on",
        "Starting. Grandpa's trick in new wrapping",
        "Starting the bypass. Packets, fasten seatbelts",
        "Launch. The honey badger says: «I'm here'sies!»",
        "Starting the «internet repair tool»",
        "Starting the engine. It's glad to see you",
        "Starting. Key in, paw on the pedal",
        "Bypass on. Throttlers, heads up",
        "Starting Zapret. Open sesame",
        "Starting. Packets are lining up",
        "Starting quietly, so the TSPU box stays asleep",
        "Starting. Whoosh — nearly there",
        "Starting the engine. Warm up, shift, go",
        "Starting Zapret. No need to press F",
        "Starting. The honey badger stretches",
        "Bypass on. Hang in there, YouTube",
        "Starting. Hello, internet!",
        "Starting the engine. Lights, camera, packets!",
        "Starting. No duct tape required",
        "Starting Zapret. Please bear with us one second",
        "Starting. Operating as normal, as they say",
        "Starting the bypass. Customs, get the stamp ready",
        "Starting. Packets are getting their briefing",
        "Cranking the motor. The key turned",
        "Starting Zapret. Handcuffs won't be needed",
        "Starting. Time for the match to resume",
        "Starting the engine. It yawned and stood up",
        "Starting. Time for nicknames to go green",
        "Starting the bypass. These are the droids, actually",
        "Starting. The honey badger is on duty",
        "Starting Zapret. One sec, shoelaces",
        "Starting. Have you tried turning it on? We are",
    ),
    "preset_apply": (
        "Applying the preset. Changing shoes mid-run",
        "Applying the preset. Packets learn new tricks",
        "Switching presets. TSPU box, new trick incoming",
        "Applying the preset. One sec, new disguise",
        "Applying. The old preset waves goodbye",
        "Applying the preset. Magic numbers in place",
        "Applying the preset. RKN-chan, it's a new hat",
        "Swapping presets like a tyre at a pit stop",
        "Applying the preset. Packets are changing outfits",
        "Applying. What the preset says is what runs",
        "Applying the preset. Not a line of our own",
        "Applying the preset. Stormtrooper RX-78 takes notes",
        "Applying. Tambourine retuned for the new preset",
        "Applying the preset. Our turn to change settings",
        "Applying the preset. Whoosh — a different toolkit",
        "Applying. The engine reads the preset aloud",
        "Applying the preset. Spicy hex values rolling",
        "Applying the preset. Black box, guess which one",
        "Switching presets. The honey badger didn't slow down",
        "Applying the preset. Packets, new orders",
        "Applying. As written, so it shall be",
        "Applying the preset. Reloading the tricks",
        "Applying the preset. DPI doorman, new rules",
        "Applying. The engine nods: «Copy that»",
        "Applying the preset. One sec, retying laces",
        "Applying the preset. New plan, same honey badger",
        "Applying. The preset is the truth, we just obey",
        "Applying the preset. Scenery change",
        "Applying the preset. Packets get new roles",
        "Switching presets. Quick as a blink",
        "Applying the preset. Grandpa's trick, take two",
        "Applying. The engine flips to a new script",
        "Applying the preset. Surprise, throttlers",
        "Applying the preset. Okay, let's go",
        "Applying. Moving tricks out of the suitcase",
        "Applying the preset. Don't ask about «-9.5»",
        "Applying the preset. Checking it line by line",
        "Applying the preset. Shift change for packets",
        "Applying. One second for a costume change",
        "Applying the preset. TSPU box, don't get attached",
        "Applying the preset. New broom, same internet",
        "Applying. By the book, no improvising",
        "Applying the preset. Re-forming the column",
        "Applying the preset. Changing of the guard",
        "Applying. Engine: «Oh, so that's how it is now»",
        "Applying the preset. Fresh moustaches for packets",
        "Applying the preset. Restart with a new plan",
        "Applying. The preset said it, the engine did it",
        "Applying the preset. A fresh deck of tricks",
        "Applying the preset. Nearly done, honest",
    ),
    "engine_stop": (
        "Stopping Zapret. The honey badger takes off its helmet",
        "Stopping. Packets, at ease, dismissed",
        "Cutting the engine. It sighed and went quiet",
        "Stopping the bypass. TSPU box, you may exhale",
        "Stopping. Disguises go back to the cloakroom",
        "Stopping Zapret. RKN-chan, your shift",
        "Switching off. Tambourine back in its case",
        "Stopping. Packets peel off their moustaches",
        "Stopping the engine. Key out of the ignition",
        "Stopping. Thanks for a day without a ban",
        "Stopping the bypass. Closing the window a bit",
        "Stopping. The honey badger goes for tea",
        "Killing the motor. Slow and steady, now parked",
        "Stopping Zapret. Stormtrooper RX-78, stand down",
        "Stopping. Tricks go back in the suitcase",
        "Stopping. Packets head home",
        "Bypass off. Internet, you're on your own",
        "Stopping. Thank you, engine, you're free",
        "Stopping Zapret. Curtain",
        "Stopping. Magic numbers go in the safe",
        "Stopping. DPI doorman, enjoy the boredom",
        "Stopping the engine. Braking gently",
        "Stopping. Rolling up the duct tape",
        "Stopping Zapret. The honey badger yawned",
        "Stopping. Shift change: nobody on duty",
        "Switching off. Now it really is «by itself»",
        "Stopping the bypass. Black boxes, all clear",
        "Stopping. Packets hand back their props",
        "Stopping the engine. Last lap",
        "Stopping. One sec, packing up",
        "Stopping Zapret. Lights out",
        "Stopping. Engine: «Finally, a break»",
        "Stopping. Throttlers, behave while we're gone",
        "Stopping the bypass. Nap time for packets",
        "Stopping. Helmet goes on the hook",
        "Stopping Zapret. Not goodbye",
        "Stopping. The circus leaves, the badger stays",
        "Stopping. The engine keeps its dignity",
        "Stopping. Tricks back on their shelves",
        "Stopping Zapret. All engines stop",
        "Stopping. Packets walk like ordinary folk",
        "Stopping. It worked, we touched it anyway",
        "Stopping. The engine waves a paw",
        "Stopping. Stand down, thanks everyone",
        "Stopping Zapret. Key's under the mat",
        "Stopping. Switch off, wipe down, tidy up",
        "Stopping the engine. Pulse slowing",
        "Stopping. No need to press F, it's planned",
        "Stopping. Honey badger: «I'll be back»",
        "Stopping Zapret. See you soon",
    ),
    "loading": (
        "Loading… the honey badger is carrying it",
        "Loading. Reticulating splines",
        "Loading. This is not throttling, honest",
        "Loading… not in 144p, don't worry",
        "Loading. No need to leave it overnight",
        "Loading. Bytes are already running",
        "Loading… five more minutes. Kidding",
        "Loading. Don't panic",
        "Loading. Thank you for your patience",
        "Loading, operating as normal",
        "Loading… whoosh. Almost",
        "Loading. Please stay on the line",
        "Loading. No outages detected",
        "Loading… the badger is looking for its glasses",
        "Loading. Not a degradation",
        "Loading. Sixteen kilobytes is not the limit",
        "Loading… lists are rustling",
        "Loading. RKN-chan had nothing to do with it",
        "Loading. Not the TSPU box's fault",
        "Loading… fetching from the top shelf",
        "Loading. One sec, blowing off the dust",
        "Loading. Making stuff up. Kidding",
        "Loading… sorting onto shelves",
        "Loading. Data is putting its shoes on",
        "Loading. The honey badger turns pages",
        "Loading… counting lines",
        "Loading. Okay, let's go",
        "Loading. Nobody dropped anything",
        "Loading… nearly, nearly",
        "Loading. No tambourine needed",
        "Loading. Data is on its way",
        "Loading… faster than the kettle",
        "Loading. Unrolling the scroll",
        "Loading. Hello there, data",
        "Loading… opening the data cupboard",
        "Loading. No worn-out servers here",
        "Loading. Line by line",
        "Loading… the honey badger stretches",
        "Loading. Quick — blink",
        "Loading. Data is lining up",
        "Loading… finding where we left it",
        "Loading. Not an F, just a second",
        "Loading. Fetching from the vault",
        "Loading… gathering it into a pile",
        "Loading. Files are saying hello",
        "Loading. All by the list",
        "Loading… about to show you",
        "Loading. Worth the wait",
        "Loading. The badger is nearly here",
        "Loading… three, two, one",
    ),
    "log_analysis": (
        "Reading the engine log. Small print, lots of it",
        "Parsing the log. winws2 has a doctor's handwriting",
        "«It worked yesterday» — looking for what changed",
        "Reading the log line by line, like a detective",
        "Finding who blocked whom. Alibis get checked",
        "Parsing the log. Spicy hex is our element",
        "Reading the log. No idea what's going on, fascinating",
        "The honey badger reads the log with a loupe and tea",
        "Counting connections. Lost count. Counting again",
        "Pairing packets with connections, like socks",
        "Long log. The engine is a bit of a novelist",
        "Looking for TSPU footprints in the log",
        "Reading the log. RKN-chan, it's private mail",
        "Sorting packets onto shelves. Many shelves",
        "The log reads like a series: one packet per episode",
        "Decoding entries. The engine wrote in a hurry",
        "Reading the log aloud, with feeling",
        "Finding where it cut off. Around kilobyte sixteen?",
        "Parsing the log. Citations will be provided",
        "The log will tell all. Questioning it politely",
        "Reading what the engine did while you looked away",
        "Counting packets. One, two… many",
        "Parsing the log. Not shamanism, just reading",
        "The log is our flight recorder, and we can open it",
        "Looking for connections hiding between the lines",
        "Reading the log. Many lines, one honey badger",
        "Sorting packets: ours, theirs, suspicious",
        "Parsing the log. Stormtrooper RX-78 would be jealous",
        "Skimming? No. Every single line",
        "Did the «fooling detector» go off? Checking",
        "Big log. Put the kettle on, we're quick",
        "Parsing entries. The engine keeps a tidy diary",
        "Reading the log. Not checking the spelling",
        "Finding who said hello and who never replied",
        "Assembling connections from lines, like a puzzle",
        "Reading the log. «What does it want?» Finding out",
        "Parsing the log. Will it take long? No. Probably",
        "Finding the second it froze. Not the 19th, surely",
        "Minuting the protocol. Bureaucrats take notes",
        "Reading the log. The small print is the fun part",
        "Engine log: many letters, little punctuation",
        "Parsing the log. «Where's the diagnostics?» Here",
        "The badger underlines the important bits in red",
        "Reading packets. One table row each",
        "Did they all arrive in the end? No spoilers",
        "Untangling a ball of connections",
        "The log is the truth. Reading the truth",
        "Needle in a log. The log is bigger than a haystack",
        "Parsing entries. We'll read the docs too. Later",
        "Reading the log. Conclusions in the table below",
    ),
}

__all__ = ["EN"]
